table dim_location
	lineageTag: da0152a7-7864-45be-a65e-896f2fb909e5

	column Country
		dataType: string
		lineageTag: ddeeceeb-1c87-4a36-9856-d92c61eedf90
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 852c8f87-fbd9-4f76-9bd2-56911690fbec
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: d3e23b30-69d3-47f8-9152-679ca3b59994
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Region
		dataType: string
		lineageTag: ae5b8e9c-828a-4e11-a9ca-14ad140ce149
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition dim_location = m
		mode: import
		queryGroup: 'Data\dim tables'
		source =
				let
				    Source = fact_employee,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Region", "Country", "Latitude", "Longitude"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Country", "Latitude", "Longitude", "Region"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

