table employee_feedback_survey
	lineageTag: 26403e01-807b-4741-af4f-62d5dbbe6240

	column 'Employee ID'
		dataType: int64
		formatString: 0
		lineageTag: 39525a4f-1356-47dd-913b-79957010af9b
		summarizeBy: count
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4cc824f9-15a9-4c53-a7a6-e3c693631b10
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Performance Feedback ID'
		dataType: int64
		formatString: 0
		lineageTag: 62ab65de-9dc8-4bb8-81ed-f690b3480aa3
		summarizeBy: count
		sourceColumn: Performance Feedback ID

		annotation SummarizationSetBy = Automatic

	column 'Goal Clarity'
		dataType: string
		lineageTag: b6a0bb61-be0a-4aac-a4a8-8f3abab2ec00
		summarizeBy: none
		sourceColumn: Goal Clarity

		annotation SummarizationSetBy = Automatic

	column 'Support for Goals'
		dataType: string
		lineageTag: 05722abe-3dea-4db4-a782-ee6753b29346
		summarizeBy: none
		sourceColumn: Support for Goals

		annotation SummarizationSetBy = Automatic

	column 'Manager Feedback Effectiveness'
		dataType: int64
		formatString: 0
		lineageTag: 03828dc8-942d-4e5a-b5c3-d568889bb048
		summarizeBy: sum
		sourceColumn: Manager Feedback Effectiveness

		annotation SummarizationSetBy = Automatic

	column 'Team Collaboration Score'
		dataType: int64
		formatString: 0
		lineageTag: c8181c89-5457-44aa-87a6-2b3c36012018
		summarizeBy: sum
		sourceColumn: Team Collaboration Score

		annotation SummarizationSetBy = Automatic

	column 'Additional Support Needed'
		dataType: string
		lineageTag: 85eb0c8e-59cf-4c7c-8f69-61a5ebe6c747
		summarizeBy: none
		sourceColumn: Additional Support Needed

		annotation SummarizationSetBy = Automatic

	column 'Career Growth Satisfaction'
		dataType: string
		lineageTag: 6fa5bcc3-f4fe-4615-b678-d0dbc280e94d
		summarizeBy: none
		sourceColumn: Career Growth Satisfaction

		annotation SummarizationSetBy = Automatic

	column 'Overall Performance Rating'
		dataType: int64
		formatString: 0
		lineageTag: d8220822-3fd9-4a9e-af16-2a1c713aa4df
		summarizeBy: sum
		sourceColumn: Overall Performance Rating

		annotation SummarizationSetBy = Automatic

	partition employee_feedback_survey = m
		mode: import
		queryGroup: Data\other
		source =
				let
				    Source = Csv.Document(File.Contents(#"Folder Path" &  "\employee_feedback_survey.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee ID", Int64.Type}, {"Year", Int64.Type}, {"Performance Feedback ID", Int64.Type}, {"Goal Clarity", type text}, {"Support for Goals", type text}, {"Manager Feedback Effectiveness", Int64.Type}, {"Team Collaboration Score", Int64.Type}, {"Additional Support Needed", type text}, {"Career Growth Satisfaction", type text}, {"Overall Performance Rating", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

