table fact_performance
	lineageTag: daefe653-4dbd-4cff-818a-b13040e6f3d4

	/// Unique identifier for each employee
	column 'Employee ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 566e5b82-58b2-4d8c-9010-94a77e0cedff
		summarizeBy: none
		sourceColumn: Employee ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Year of the performance review
	column 'Performance Review Year'
		dataType: int64
		formatString: 0
		lineageTag: b27f7c8c-1cd3-4f02-93ba-f6ef8bdaa15e
		summarizeBy: sum
		sourceColumn: Performance Review Year

		annotation SummarizationSetBy = Automatic

	/// Rating assigned during performance review year
	column 'Performance Rating'
		dataType: int64
		formatString: 0
		lineageTag: cad0f049-016b-4850-a7a9-ffc056549799
		summarizeBy: sum
		sourceColumn: Performance Rating

		annotation SummarizationSetBy = Automatic

	/// Number of projects completed by the employee in the review period
	column 'Projects Handled'
		dataType: int64
		formatString: 0
		lineageTag: ecb0757f-0df0-4970-8869-2402464b0008
		summarizeBy: sum
		sourceColumn: Projects Handled

		annotation SummarizationSetBy = Automatic

	/// Number of projects the employee was expected to complete
	column 'Project Target'
		dataType: int64
		formatString: 0
		lineageTag: 8aa3d0ce-c892-4454-98e1-9263768c8421
		summarizeBy: sum
		sourceColumn: Project Target

		annotation SummarizationSetBy = Automatic

	/// Total working hours for the employee in the review period
	column 'Working Hours'
		dataType: int64
		formatString: 0
		lineageTag: 87828cb7-50e1-48fd-8073-dcf2b09c8a1d
		summarizeBy: sum
		sourceColumn: Working Hours

		annotation SummarizationSetBy = Automatic

	/// Total overtime hours worked in the review year
	column Overtime
		dataType: int64
		formatString: 0
		lineageTag: 83ab7b9a-2adb-4305-addb-110639717899
		summarizeBy: sum
		sourceColumn: Overtime

		annotation SummarizationSetBy = Automatic

	/// Number of team members the employee worked with or led
	column 'Team Size'
		dataType: int64
		formatString: 0
		lineageTag: 3d03a84c-66f7-4456-b7b4-cf0c11e7a569
		summarizeBy: sum
		sourceColumn: Team Size

		annotation SummarizationSetBy = Automatic

	/// Assessment of the employee’s potential for growth or promotion
	column 'Potential Rating'
		dataType: string
		lineageTag: c31478dd-15ec-4a57-8a8f-3e519e35f05e
		summarizeBy: none
		sourceColumn: Potential Rating

		annotation SummarizationSetBy = Automatic

	/// Employee satisfaction level on a scale of 1 to 5
	column 'Satisfaction Score'
		dataType: int64
		formatString: 0
		lineageTag: 2b1fae8d-ba59-494b-80c6-b02c05a42633
		summarizeBy: sum
		sourceColumn: Satisfaction Score

		annotation SummarizationSetBy = Automatic

	/// Yearly incentive earned by the employee
	column 'Incentive Amount ($)'
		dataType: double
		lineageTag: 45b1a3a5-8323-4223-a8b5-27e0de3edf4d
		summarizeBy: sum
		sourceColumn: Incentive Amount ($)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Yearly bonus earned by the employee
	column 'Bonus ($)'
		dataType: double
		lineageTag: 0f008646-be5e-4cac-87eb-31fdc394adc2
		summarizeBy: sum
		sourceColumn: Bonus ($)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_performance = m
		mode: import
		queryGroup: 'Data\fact tables'
		source =
				let
				    Source = Csv.Document(File.Contents(#"Folder Path" & "\performance.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee ID", Int64.Type}, {"Performance Review Year", Int64.Type}, {"Performance Rating", Int64.Type}, {"Projects Handled", Int64.Type}, {"Project Target", Int64.Type}, {"Working Hours", Int64.Type}, {"Overtime", Int64.Type}, {"Team Size", Int64.Type}, {"Potential Rating", type text}, {"Satisfaction Score", Int64.Type}, {"Incentive Amount ($)", type number}, {"Bonus ($)", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

