table fact_resigned
	lineageTag: e4107b65-c226-4c19-8d5e-3dec769a38c0

	column 'Employee ID'
		dataType: int64
		formatString: 0
		lineageTag: 613cd323-c0ce-4c77-90ef-b782d9ae08d4
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Resignation Reason ID'
		dataType: int64
		formatString: 0
		lineageTag: 79f82322-1be1-4786-baab-afd831fdaaea
		summarizeBy: none
		sourceColumn: Resignation Reason ID

		annotation SummarizationSetBy = Automatic

	column 'Resigned Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69fed67f-12e4-47a1-ab39-60a473e8ca6f
		summarizeBy: none
		sourceColumn: Resigned Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Resigned Type'
		dataType: string
		lineageTag: f38bf0cb-f921-46c3-9f29-17abc04d3452
		summarizeBy: none
		sourceColumn: Resigned Type

		annotation SummarizationSetBy = Automatic

	column 'Work Environment Feedback'
		dataType: string
		lineageTag: 020d871b-3232-4b97-a35c-e13d5f5b2d93
		summarizeBy: none
		sourceColumn: Work Environment Feedback

		annotation SummarizationSetBy = Automatic

	column 'Management/Team Experience Score'
		dataType: int64
		formatString: 0
		lineageTag: e23a9b56-8c2d-4b79-a628-9a393f3f9bef
		summarizeBy: sum
		sourceColumn: Management/Team Experience Score

		annotation SummarizationSetBy = Automatic

	column 'Level at Exit'
		dataType: string
		lineageTag: 95937524-4124-49d7-b943-159caf8d5270
		summarizeBy: none
		sourceColumn: Level at Exit

		annotation SummarizationSetBy = Automatic

	partition fact_resigned = m
		mode: import
		queryGroup: 'Data\fact tables'
		source =
				let
				    Source = Csv.Document(File.Contents(#"Folder Path" & "\resigned_table.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee ID", Int64.Type}, {"Resigned Date", type date}, {"Resigned Type", type text}, {"Resigned Reason", type text}, {"Work Environment Feedback", type text}, {"Management/Team Experience Score", Int64.Type}, {"Level at Exit", type text}, {"Resignation Reason ID", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Resigned Reason"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Employee ID", "Resignation Reason ID", "Resigned Date", "Resigned Type", "Work Environment Feedback", "Management/Team Experience Score", "Level at Exit"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

