{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Folder Path\",\"fact_employee\",\"employee_feedback_survey\",\"exit_interview_survey\",\"fact_leave\",\"fact_performance\",\"dim_resignationReason\",\"fact_resigned\",\"fact_training\",\"dim_trainingSession\",\"dim_employee\",\"dim_location\",\"dim_department\",\"dim_jobtitle\",\"dim_leaveReason\",\"dim_leaveType\",\"Date Parameter\",\"date\",\"_measure\",\"resignation_prediction\",\"f1 score\",\"Performance-9Box\",\"Potential-9Box\",\"9-Box Grid\",\"Profile of Employee\",\"Information of Age, Assessment Potential, Assessment Performance\",\"Only All\",\"Full All\",\"Handled+Targeted+Working Hours+Overtime\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_RemovedChildren",
        "value": "[{\"remoteItemId\":{\"foreignKeyRelationship\":{\"fromTableLocalLineageTag\":\"32cefa14-f476-42c8-858e-a58b3f95b380\",\"fromColumnLocalLineageTag\":\"19ec7a4c-f6f0-4d34-b037-9e3a2ac8be9a\",\"toTableLocalLineageTag\":\"24b5c18d-87f2-415d-bf65-36f89420f2c8\",\"toColumnLocalLineageTag\":\"094d7d87-5728-40f9-9b65-51e995618d68\"}},\"objectType\":\"Relationship\"},{\"remoteItemId\":{\"foreignKeyRelationship\":{\"fromTableLocalLineageTag\":\"8c2b2965-eeb0-4753-b286-db0c311efcc5\",\"fromColumnLocalLineageTag\":\"7bf82b72-3d23-4b0c-8e8a-307132c874f1\",\"toTableLocalLineageTag\":\"17b58dde-a5cd-4358-a7cf-80afe5bb402e\",\"toColumnLocalLineageTag\":\"3e3b28e2-166d-4b18-8862-9d88add70bc0\"}},\"objectType\":\"Relationship\"}]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Folder Path",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"D:\\high performance project\\project\\dataset final\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ff0fe4ac-6dc7-4cf2-8195-dba1ca802663",
        "queryGroup": "folder path"
      },
      {
        "name": "Date Parameter",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let fnDateTable = (StartDate as date, EndDate as date, FYStartMonth as number) as table =>",
          "  let",
          "    DayCount = Duration.Days(Duration.From(EndDate - StartDate)),",
          "    Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
          "    TableFromList = Table.FromList(Source, Splitter.SplitByNothing()),   ",
          "    ChangedType = Table.TransformColumnTypes(TableFromList,{{\"Column1\", type date}}),",
          "    RenamedColumns = Table.RenameColumns(ChangedType,{{\"Column1\", \"Date\"}}),",
          "    InsertYear = Table.AddColumn(RenamedColumns, \"Year\", each Date.Year([Date]),type text),",
          "    InsertYearNumber = Table.AddColumn(RenamedColumns, \"YearNumber\", each Date.Year([Date])),",
          "    InsertQuarter = Table.AddColumn(InsertYear, \"QuarterOfYear\", each Date.QuarterOfYear([Date])),",
          "    InsertMonth = Table.AddColumn(InsertQuarter, \"MonthOfYear\", each Date.Month([Date]), type text),",
          "    InsertDay = Table.AddColumn(InsertMonth, \"DayOfMonth\", each Date.Day([Date])),",
          "    InsertDayInt = Table.AddColumn(InsertDay, \"DateInt\", each [Year] * 10000 + [MonthOfYear] * 100 + [DayOfMonth]),",
          "    InsertMonthName = Table.AddColumn(InsertDayInt, \"MonthName\", each Date.ToText([Date], \"MMMM\"), type text),",
          "    InsertCalendarMonth = Table.AddColumn(InsertMonthName, \"MonthInCalendar\", each (try(Text.Range([MonthName],0,3)) otherwise [MonthName]) & \" \" & Text.End(Number.ToText([Year]), 2)),",
          "    InsertCalendarQtr = Table.AddColumn(InsertCalendarMonth, \"QuarterInCalendar\", each \"Q\" & Number.ToText([QuarterOfYear]) & \" \" & Number.ToText([Year])),",
          "    InsertDayWeek = Table.AddColumn(InsertCalendarQtr, \"DayInWeek\", each if Date.DayOfWeek([Date], Day.Sunday) = 0 then 7 else Date.DayOfWeek([Date], Day.Sunday)),",
          "    InsertDayName = Table.AddColumn(InsertDayWeek, \"DayOfWeekName\", each Date.ToText([Date], \"dddd\"), type text),",
          "    InsertWeekEnding = Table.AddColumn(InsertDayName, \"WeekEnding\", each Date.EndOfWeek([Date]), type date),",
          "    InsertWeekNumber= Table.AddColumn(InsertWeekEnding, \"Week Number\", each Date.WeekOfYear([Date])),",
          "    InsertMonthnYear = Table.AddColumn(InsertWeekNumber,\"MonthnYear\", each [Year] * 10000 + [MonthOfYear] * 100),",
          "    InsertQuarternYear = Table.AddColumn(InsertMonthnYear,\"QuarternYear\", each [Year] * 10000 + [QuarterOfYear] * 100),",
          "    ChangedType1 = Table.TransformColumnTypes(InsertQuarternYear,{{\"QuarternYear\", Int64.Type},{\"Week Number\", Int64.Type},{\"Year\", type text},{\"MonthnYear\", Int64.Type}, {\"DateInt\", Int64.Type}, {\"DayOfMonth\", Int64.Type}, {\"MonthOfYear\", Int64.Type}, {\"QuarterOfYear\", Int64.Type}, {\"MonthInCalendar\", type text}, {\"QuarterInCalendar\", type text}, {\"DayInWeek\", Int64.Type}}),",
          "    InsertShortYear = Table.AddColumn(ChangedType1, \"ShortYear\", each Text.End(Text.From([Year]), 2), type text),",
          "    AddFY = Table.AddColumn(InsertShortYear, \"FY\", each \"FY\"&(if [MonthOfYear]>=FYStartMonth then Text.From(Number.From([ShortYear])+1) else [ShortYear]))",
          "in",
          "    AddFY",
          "in",
          "    fnDateTable"
        ],
        "kind": "m",
        "lineageTag": "e21b802f-ebb0-4e1b-bfe7-a420489eef4a",
        "queryGroup": "Calender"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "folder path"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Data\\fact tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Data\\dim tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Data\\other"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "Calender"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_d9a350a3-8d47-4bb9-895c-36a300aaca9a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Employee ID",
        "fromTable": "fact_leave",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "AutoDetected_06532fbf-9cf2-41fd-99f0-b79f36529192",
        "fromColumn": "Employee ID",
        "fromTable": "fact_performance",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "AutoDetected_81ce10c7-dae6-450d-89ed-4d3cc91fb9ca",
        "fromColumn": "Employee ID",
        "fromTable": "fact_training",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "AutoDetected_a428936d-116f-4d5c-8dc5-79601860a859",
        "fromColumn": "Country",
        "fromTable": "dim_employee",
        "isActive": false,
        "toColumn": "Country",
        "toTable": "dim_location"
      },
      {
        "name": "AutoDetected_658e591b-899a-4c4d-9af3-46c7167e88d1",
        "fromColumn": "Leave Details",
        "fromTable": "fact_leave",
        "toColumn": "Leave Details",
        "toTable": "dim_leaveReason"
      },
      {
        "name": "AutoDetected_80558a47-a8b6-4f55-a5bf-3f12f0edba7f",
        "fromColumn": "Leave Type",
        "fromTable": "fact_leave",
        "toColumn": "Leave Type",
        "toTable": "dim_leaveType"
      },
      {
        "name": "AutoDetected_5fa65ad6-a4b2-4fe2-9b13-7a221bc0d25a",
        "fromColumn": "Resignation Reason ID",
        "fromTable": "fact_resigned",
        "toColumn": "Resignation Reason ID",
        "toTable": "dim_resignationReason"
      },
      {
        "name": "AutoDetected_75d24dcd-3a0a-456f-b7c5-67d67add5930",
        "fromColumn": "Training Session ID",
        "fromTable": "fact_training",
        "toColumn": "Training Session ID",
        "toTable": "dim_trainingSession"
      },
      {
        "name": "233590bb-dd77-20a2-26bb-e6eee75dd3b0",
        "fromColumn": "Employee ID",
        "fromTable": "fact_resigned",
        "toColumn": "Employee ID",
        "toTable": "exit_interview_survey"
      },
      {
        "name": "34b4582f-a601-2eda-3b26-5732f9c682b7",
        "fromColumn": "Department",
        "fromTable": "fact_employee",
        "toColumn": "Department",
        "toTable": "dim_department"
      },
      {
        "name": "d4b052f7-4f8f-3fad-ebac-4da8630293e8",
        "fromColumn": "Job Title",
        "fromTable": "fact_employee",
        "toColumn": "Job Title",
        "toTable": "dim_jobtitle"
      },
      {
        "name": "56a77f6f-a7bb-c282-cd11-89ba1dd085b8",
        "fromColumn": "Employee ID",
        "fromTable": "fact_employee",
        "toColumn": "Employee ID",
        "toTable": "dim_employee"
      },
      {
        "name": "57d3b46f-cd35-649d-950e-c71283c8975c",
        "fromColumn": "Employee ID",
        "fromTable": "employee_feedback_survey",
        "isActive": false,
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "a5451bef-f212-7b9b-8316-595258eac298",
        "fromColumn": "Hire Date",
        "fromTable": "fact_employee",
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "38946a96-8f44-668a-93ed-072f935d0a5e",
        "fromColumn": "Leave Start Date",
        "fromTable": "fact_leave",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "cfa48681-87f3-6093-4e08-ea2b6df4c45c",
        "fromColumn": "Leave End Date",
        "fromTable": "fact_leave",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "504fbd3f-d7b3-b4bf-a0ea-6e52511bdd12",
        "fromColumn": "Training Completion Date",
        "fromTable": "fact_training",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "e1fe8253-8d2d-4712-5ed9-b9845f41e460",
        "fromColumn": "Resigned Date",
        "fromTable": "fact_resigned",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "b83f3a18-c589-84a3-9b0d-47489f748b50",
        "fromColumn": "Month Name",
        "fromTable": "dim_employee",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "2ff8e4e3-0591-a925-2ae6-1bb5abf655ad",
        "fromColumn": "Employee ID",
        "fromTable": "fact_resigned",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "89aabce8-b9d9-bed2-a985-fd934a185e58",
        "fromColumn": "Employee ID",
        "fromTable": "fact_resigned",
        "isActive": false,
        "toColumn": "Employee ID",
        "toTable": "dim_employee"
      },
      {
        "name": "df284f29-a08a-15b4-cc7f-c3d88d4ec5fc",
        "fromColumn": "Employee ID",
        "fromTable": "fact_employee",
        "toColumn": "Employee ID",
        "toTable": "resignation_prediction"
      },
      {
        "name": "c3b75f0e-e1d7-84ef-898f-a996c68b8de6",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Employee ID",
        "fromTable": "Performance-9Box",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "dc1c6592-ebc7-be4d-e606-212e3544b368",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Employee ID",
        "fromTable": "Potential-9Box",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "65a576a0-c17c-7ae1-d904-25ea6c215ca7",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Employee ID",
        "fromTable": "9-Box Grid",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "033d4b2f-4221-0bae-9496-eeeea8054899",
        "fromColumn": "Employee ID",
        "fromTable": "fact_performance",
        "isActive": false,
        "toColumn": "Employee ID",
        "toTable": "9-Box Grid"
      },
      {
        "name": "1f210124-b496-41bf-bf02-700ded243fe6",
        "fromColumn": "Employee ID",
        "fromTable": "Basic_Salary_Payroll",
        "toColumn": "Employee ID",
        "toTable": "dim_employee"
      },
      {
        "name": "a30467c0-379e-562f-d406-73e63199a4e2",
        "fromColumn": "Date",
        "fromTable": "Basic_Salary_Payroll",
        "toColumn": "Date",
        "toTable": "date"
      },
      {
        "name": "a32139c0-0953-4e82-9e69-b22a7103e6dc",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Employee ID",
        "fromTable": "fact_performance",
        "isActive": false,
        "toColumn": "Employee ID",
        "toTable": "dim_employee"
      },
      {
        "name": "e480951b-ab51-2b60-fe8b-938e4a2f7de6",
        "fromColumn": "Employee ID",
        "fromTable": "Full All",
        "toColumn": "Employee ID",
        "toTable": "fact_employee"
      },
      {
        "name": "2b4657c3-6354-4d78-9d67-e5755efb2642",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Employee ID",
        "fromTable": "fact_performance",
        "isActive": false,
        "toColumn": "Employee ID",
        "toTable": "resignation_prediction"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "fact_employee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each employee",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5cf91ff1-ed33-4718-93e7-c97c637556d1",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Full name of the employee",
            "lineageTag": "0f34d61e-f590-4418-b29c-9c83ffa1882e",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date of Birth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Birth date of the employee",
            "formatString": "Long Date",
            "lineageTag": "fbf472c5-a687-46fe-a325-915a927d6e15",
            "sourceColumn": "Date of Birth",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Gender identity of the employee",
            "lineageTag": "1f12caee-9b9e-44ca-a2fd-b4fe86f5ae4e",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Education Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Highest education level attained by the employee",
            "lineageTag": "33e7bd3a-c6f0-4081-9f00-95921877f651",
            "sourceColumn": "Education Level",
            "summarizeBy": "none"
          },
          {
            "name": "Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the employee was hired",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "d5fc471d-c165-454e-bc1e-30ebaada1b40",
            "sourceColumn": "Hire Date",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Department or functional area the employee belongs to",
            "isHidden": true,
            "lineageTag": "7d043d37-2d88-41cd-993f-a1f3ecf05dce",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Job title or position held by the employee",
            "isHidden": true,
            "lineageTag": "8705da77-86f1-44e0-a683-98fd2a84c62f",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "Organization Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Level in the organization hierarchy",
            "isHidden": true,
            "lineageTag": "a8654d4d-f4a3-4068-807b-aa6b61939879",
            "sourceColumn": "Organization Level",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Region of the country employee belong to",
            "isHidden": true,
            "lineageTag": "22d15ccd-d610-4285-8e54-ea57e885b075",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Country of the employee",
            "isHidden": true,
            "lineageTag": "f7d94127-e57b-4656-ac79-7da65a3cf563",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": [
              "Latitude coordinate of the employees",
              "location"
            ],
            "isHidden": true,
            "lineageTag": "de659c86-57d2-4312-82dd-ad054e954878",
            "sourceColumn": "Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Longitude coordinate of the employees location",
            "isHidden": true,
            "lineageTag": "f16f2c4a-93a6-4e19-b3a8-0bb5fab02c76",
            "sourceColumn": "Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Employment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Onsite or remote work status",
            "lineageTag": "acea19cb-1347-41b0-8d5e-a77956fcc64a",
            "sourceColumn": "Employment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Employment Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Employment type, indicating full-time or part-time status",
            "lineageTag": "affd95fb-cbf2-4820-b2bf-677ce5e898b7",
            "sourceColumn": "Employment Type",
            "summarizeBy": "none"
          },
          {
            "name": "Base Salary ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": "Yearly base salary of the employee",
            "lineageTag": "6ce1e629-a6bc-4bd9-8b2f-522323d29080",
            "sourceColumn": "Base Salary ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Times Promoted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Number of times the employee has been promoted",
            "formatString": "0",
            "lineageTag": "3d73fbfb-58ad-4d4f-8231-ce7b896bee07",
            "sourceColumn": "Times Promoted",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Employment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Employment status indicating active or resigned status",
            "lineageTag": "b8fe43ae-8fa4-4d09-885a-157d01a70c25",
            "sourceColumn": "Current Employment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Annual Leave Entitlement (days)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Total number of leave days the employee is entitled to annually",
            "formatString": "0",
            "lineageTag": "fc8171a9-ccd0-45a9-bd01-92e511f241ca",
            "sourceColumn": "Annual Leave Entitlement (days)",
            "summarizeBy": "sum"
          },
          {
            "name": "Ethnicity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Ethnic group employee belongs to",
            "lineageTag": "ab38479a-4f6a-432d-9338-15d01dcae2ae",
            "sourceColumn": "Ethnicity",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "DATEDIFF(fact_employee[Date of Birth], TODAY(), YEAR)",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "efa5163c-847f-4d03-a4e2-b802211db055",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Age Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    fact_employee[Age] <= 25, \"18-25\",",
              "    fact_employee[Age] <= 35, \"26-35\",",
              "    fact_employee[Age] <= 45, \"36-45\",",
              "    fact_employee[Age] <= 55, \"46-55\",",
              "    fact_employee[Age] <= 66, \"56-66\",",
              "    \"Above 66\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f3603a80-be2d-48bd-a5db-68ed71497bc3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "years_at_company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF(fact_employee[Hire Date],TODAY(),YEAR)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bf8357b5-e278-44f9-8dce-15375e1f7050",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "tenure_band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(TRUE(),",
              "fact_employee[Tenure]<=1,\"<1 Year\",",
              "fact_employee[Tenure]>=1 &&fact_employee[Tenure]<=3,\"1-3 Years\",",
              "fact_employee[Tenure]>=4 && fact_employee[Tenure]<=7,\"4-6 Years\",\"6+ Years\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8391f283-e97a-4c7a-853f-2f0fd91bf7b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Salary Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    fact_employee[Base Salary ($)] < 30000, \"Below Range\",",
              "    fact_employee[Base Salary ($)] <= 50000, \"30K-50K\",",
              "    fact_employee[Base Salary ($)] <= 75000, \"50K-75K\",",
              "    fact_employee[Base Salary ($)] <= 100000, \"75K-100K\",",
              "    fact_employee[Base Salary ($)] <= 125000, \"100K-125K\",",
              "    fact_employee[Base Salary ($)] <= 150000, \"125K-150K\",",
              "    \"Above 150K\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "01a651f2-fed5-446f-8501-f3ed5edff163",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Birth Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "049f6065-0bc1-4a37-ad30-16650eb5d97a",
            "sourceColumn": "Birth Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Age by Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3c59dbc-5ed2-4919-a44a-b36e104c518c",
            "sourceColumn": "Age by Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Age Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48847b6c-77ed-40ff-9c44-6d9c728755dd",
            "sourceColumn": "Age Category",
            "summarizeBy": "none"
          },
          {
            "name": "Tenure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "(TODAY()-fact_employee[Hire Date])/365",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "5621182a-065b-498f-89b7-9f87a8b2a2e6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Actual prediction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2bcc800-4af8-43f3-ab85-c544a8d910e8",
            "sourceColumn": "Actual prediction",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e6a88bb3-3e63-4601-bbfd-7f75534a6f34",
        "partitions": [
          {
            "name": "fact_employee",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\employee.csv\"),[Delimiter=\",\", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Full Name\", type text}, {\"Date of Birth\", type date}, {\"Gender\", type text}, {\"Education Level\", type text}, {\"Hire Date\", type date}, {\"Department\", type text}, {\"Job Title\", type text}, {\"Organization Level\", type text}, {\"Region\", type text}, {\"Country\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Employment Status\", type text}, {\"Employment Type\", type text}, {\"Base Salary ($)\", type number}, {\"Times Promoted\", Int64.Type}, {\"Years at Company\", Int64.Type}, {\"Current Employment Status\", type text}, {\"Annual Leave Entitlement (days)\", Int64.Type}, {\"Ethnicity\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Years at Company\"}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Removed Columns\", \"Year\", each Date.Year([Date of Birth]), Int64.Type),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Inserted Year\",{{\"Year\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Year\", \"Birth Year\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Age\", each Date.Year(DateTime.LocalNow()) - [Birth Year]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Age\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"Age Category\", each if [Age] >= 18 and [Age] <= 25 then \"Young Adult\"",
                "else if [Age] >= 26 and [Age] <= 35 then \"Early Career Professional\"",
                "else if [Age] >= 36 and [Age] <= 45 then \"Mid-Career Professional\"",
                "else if [Age] >= 46 and [Age] <= 55 then \"Experienced Professional\"",
                "else if [Age] >= 56 and [Age] <= 66 then \"Pre-Retirement\"",
                "else \"Out of Range\"),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Age Category\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type3\", each true),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Age\", \"Age by year\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"Age by year\", \"Age Category\"}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Removed Columns1\", \"Age by Year\", each Date.Year(DateTime.LocalNow()) - [Birth Year]),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Age by Year\", Int64.Type}}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"Age Category\", each if [Age by Year] >= 18 and [Age by Year] <= 25 then \"Young Adult\"",
                "else if [Age by Year] >= 26 and [Age by Year] <= 35 then \"Early Career Professional\"",
                "else if [Age by Year] >= 36 and [Age by Year] <= 45 then \"Mid-Career Professional\"",
                "else if [Age by Year] >= 46 and [Age by Year] <= 55 then \"Senior Professional\"",
                "else if [Age by Year] >= 56 and [Age by Year] <= 66 then \"Experienced Professional\"",
                "else if [Age by Year] >66 then \"Pre-Retirement\"else \"Out of Range\"),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"Age Category\", type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type5\", each true),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Filtered Rows1\", \"Actual prediction\", each if [Current Employment Status] = \"Active\" then 0 else 0)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "employee_feedback_survey",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Identifier for each employee",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39525a4f-1356-47dd-913b-79957010af9b",
            "sourceColumn": "Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Year of the feedback Survey",
            "formatString": "0",
            "lineageTag": "4cc824f9-15a9-4c53-a7a6-e3c693631b10",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Performance Feedback ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Indetifier of the Survey",
            "formatString": "0",
            "lineageTag": "62ab65de-9dc8-4bb8-81ed-f690b3480aa3",
            "sourceColumn": "Performance Feedback ID",
            "summarizeBy": "count"
          },
          {
            "name": "Goal Clarity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Did the employee feel their goals and expectations were clearly communicated?",
            "lineageTag": "b6a0bb61-be0a-4aac-a4a8-8f3abab2ec00",
            "sourceColumn": "Goal Clarity",
            "summarizeBy": "none"
          },
          {
            "name": "Support for Goals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Did the employee receive adequate support to achieve their goals?",
            "lineageTag": "05722abe-3dea-4db4-a782-ee6753b29346",
            "sourceColumn": "Support for Goals",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Feedback Effectiveness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "How effective was the feedback provided by their manager?",
            "formatString": "0",
            "lineageTag": "03828dc8-942d-4e5a-b5c3-d568889bb048",
            "sourceColumn": "Manager Feedback Effectiveness",
            "summarizeBy": "sum"
          },
          {
            "name": "Team Collaboration Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "How well did the employees collaborate with their team to achieve goals?",
            "formatString": "0",
            "lineageTag": "c8181c89-5457-44aa-87a6-2b3c36012018",
            "sourceColumn": "Team Collaboration Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Additional Support Needed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "What additional support would help improve their performance?",
            "lineageTag": "85eb0c8e-59cf-4c7c-8f69-61a5ebe6c747",
            "sourceColumn": "Additional Support Needed",
            "summarizeBy": "none"
          },
          {
            "name": "Career Growth Satisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Are the employee satisfied with their career growth and opportunities?",
            "lineageTag": "6fa5bcc3-f4fe-4615-b678-d0dbc280e94d",
            "sourceColumn": "Career Growth Satisfaction",
            "summarizeBy": "none"
          },
          {
            "name": "Overall Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "How would the employee rate their own overall performance this period?",
            "formatString": "0",
            "lineageTag": "d8220822-3fd9-4a9e-af16-2a1c713aa4df",
            "sourceColumn": "Overall Performance Rating",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "26403e01-807b-4741-af4f-62d5dbbe6240",
        "partitions": [
          {
            "name": "employee_feedback_survey",
            "mode": "import",
            "queryGroup": "Data\\other",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" &  \"\\employee_feedback_survey.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Year\", Int64.Type}, {\"Performance Feedback ID\", Int64.Type}, {\"Goal Clarity\", type text}, {\"Support for Goals\", type text}, {\"Manager Feedback Effectiveness\", Int64.Type}, {\"Team Collaboration Score\", Int64.Type}, {\"Additional Support Needed\", type text}, {\"Career Growth Satisfaction\", type text}, {\"Overall Performance Rating\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "exit_interview_survey",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each employee",
            "formatString": "0",
            "lineageTag": "fdc4461f-ad06-4c09-b17c-7b9e0ac41873",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Exit Interview ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each exit interview",
            "formatString": "0",
            "lineageTag": "6f3e71f4-445d-4a6c-8e6a-0020301e79cf",
            "sourceColumn": "Exit Interview ID",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Resignation Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Primary reason for decision to leave",
            "lineageTag": "056077a2-c063-4402-8917-b06132bf5716",
            "sourceColumn": "Primary Resignation Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Work Environment Satisfaction Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": [
              "Satisfaction rate with the work",
              "environment"
            ],
            "formatString": "0",
            "lineageTag": "5a861f72-2614-4e3f-b966-ed70ec4ef8d6",
            "sourceColumn": "Work Environment Satisfaction Score",
            "summarizeBy": "none"
          },
          {
            "name": "Support Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Did the employee feel supported in their role with adequate resources",
            "lineageTag": "e24e622a-f08c-4166-9e62-0de7ba335da9",
            "sourceColumn": "Support Received",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "962dcf3d-53c0-4da3-90aa-c40ad780fe00",
        "partitions": [
          {
            "name": "exit_interview_survey",
            "mode": "import",
            "queryGroup": "Data\\other",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\exit_interview_survey.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Exit Interview ID\", Int64.Type}, {\"Primary Resignation Reason\", type text}, {\"Work Environment Satisfaction Score\", Int64.Type}, {\"Support Received\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_leave",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Unique identifier for each employee",
            "lineageTag": "26127b9c-a0db-4b8d-abb2-a8098389c6f0",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Leave Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Short description of the reason for leave",
            "isHidden": true,
            "lineageTag": "f2ed6037-807a-4801-91f9-991febc5faf7",
            "sourceColumn": "Leave Details",
            "summarizeBy": "none"
          },
          {
            "name": "Leave Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "Type of leave taken by the employee",
            "lineageTag": "a9efbaf1-2460-422d-a4c8-e5e16b9521c2",
            "sourceColumn": "Leave Type",
            "summarizeBy": "none"
          },
          {
            "name": "Leave Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the leave period begins",
            "formatString": "Long Date",
            "lineageTag": "b9b4ae5b-4049-444c-b4ff-948c9bf70480",
            "sourceColumn": "Leave Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Leave End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the leave period ends",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "53576719-c68d-40a1-b5a4-fe39d0405b61",
            "sourceColumn": "Leave End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Leave Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Approval status of the leave request",
            "lineageTag": "ffe0b38f-e07d-4fec-a292-7800bdad9bed",
            "sourceColumn": "Leave Status",
            "summarizeBy": "none"
          },
          {
            "name": "Leave Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "description": "Remaining leave days available to the employee",
            "formatString": "0",
            "lineageTag": "4669615c-8398-4d91-84fd-123531706661",
            "sourceColumn": "Leave Balance",
            "summarizeBy": "none"
          },
          {
            "name": "Cost of Leave ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "description": "Monetary cost associated with the leave taken",
            "formatString": "0",
            "lineageTag": "951ecfe8-6c5d-4bdb-ab8d-ab6b30c8c29a",
            "sourceColumn": "Cost of Leave ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Leave Liability Amount ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Cost of leave liability for the employee",
            "lineageTag": "0fb6fc38-9530-4770-985d-c6c169be7a9c",
            "sourceColumn": "Leave Liability Amount ($)",
            "summarizeBy": "none"
          },
          {
            "name": "Absenteeism Cost Impact ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "description": "Financial impact of absenteeism on productivity or department costs",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b871671d-51da-47d1-9ad7-fd720794ca8a",
            "sourceColumn": "Absenteeism Cost Impact ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Days on Leave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('fact_leave'[Leave Status]=\"Approved\", DATEDIFF('fact_leave'[Leave Start Date], 'fact_leave'[Leave End Date],DAY),0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2c26d6d8-4499-4d22-9223-07bf8397b495",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED(fact_employee[Age])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1253c245-2a0c-4232-b48b-ddf63a3ea8e5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AgeRange",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    fact_leave[Age] <= 25, \"18-25\",",
              "    fact_leave[Age] <= 35, \"26-35\",",
              "    fact_leave[Age] <= 45, \"36-45\",",
              "    fact_leave[Age] <= 55, \"46-55\",",
              "    fact_leave[Age] <= 70, \"56-65+\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "28ab6008-4414-4d88-9152-9cd6c34d49b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Annual Leave Entitlement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED(fact_employee[Annual Leave Entitlement (days)])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c19dca88-c9f2-44c1-93f2-577acbf8496e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Annual Leave Liability",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "fact_leave[Leave Balance]*fact_leave[Cost of Leave ($)]",
            "isDataTypeInferred": true,
            "lineageTag": "ef0c93dc-fe70-4554-a333-6ef5a6f2c1d3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(fact_leave[Leave Start Date])",
            "formatString": "0",
            "lineageTag": "84954c4c-ecde-44be-8ea1-f223edc6c011",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('fact_leave'[Leave Start Date],\"YYYY-MM\")",
            "isDataTypeInferred": true,
            "lineageTag": "08420645-446d-457f-9bb5-166e16b48239",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cost Per Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "DIVIDE(SUM('fact_leave'[Cost of Leave ($)]),SUM('fact_leave'[Days on Leave]),0)",
            "formatString": "0",
            "lineageTag": "56233fb0-3326-4272-84a7-8b14b682e21a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Remaining Leave Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "(fact_leave[Annual Leave Entitlement])- ('fact_leave'[Days on Leave])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "913b7cdb-c7bd-4aee-adc3-776631a3042b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Cost Of Remaining Annual Leave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "expression": "'fact_leave'[Remaining Leave Days]*'fact_leave'[Cost Per Day]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fa2a873d-83e8-4566-a2a4-3c3c73e636b8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Weekday Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('fact_leave'[Leave Start Date],\"dddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "d4172605-0783-4921-ae20-63272d1c08c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "RELATED(fact_employee[Hire Date])",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "f5c754a5-3490-4d6c-978f-c8c22f36049b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Tenure Years",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF(fact_leave[Hire Date],TODAY(),YEAR)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ef10af0d-1f72-42d4-9259-b93a36ff43ab",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tenure Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'fact_leave'[Tenure Years] <= 1, \"0-1 Year\",",
              "    'fact_leave'[Tenure Years] <= 3, \"1-3 Years\",",
              "    'fact_leave'[Tenure Years] <= 5, \"3-5 Years\",",
              "    'fact_leave'[Tenure Years] <= 10, \"5-10 Years\",",
              "    \"10+Years\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e8156f63-d425-4492-affc-bdadcebbaab8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "expression": "RELATED('9-Box Grid'[Assessment Performance Rating])",
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "lineageTag": "f662cbb7-7827-436a-af7b-97f64366ac1c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Absenteeism Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(SUM('fact_leave'[Days on Leave]),260,0)",
            "isDataTypeInferred": true,
            "lineageTag": "3933c975-5bbe-4f16-8d45-b8cc0313a0fc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Average Performance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "AVERAGE(fact_leave[Performance Rating])",
            "isDataTypeInferred": true,
            "lineageTag": "9a9c449e-f81a-4f0b-8443-87c3cc858524",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Absenteeism Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "SUM(fact_leave[Absenteeism Cost Impact ($)])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c3e707a0-9e8f-4f7b-8f93-a55ae2daeafd",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "81376d4a-6a2f-4308-9e15-b8d0bb7595f0",
        "partitions": [
          {
            "name": "fact_leave",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\leave.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Leave Start Date\", type date}, {\"Leave End Date\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Leave Reason ID\", \"Number of Leave Days Taken\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_performance",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each employee",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "566e5b82-58b2-4d8c-9010-94a77e0cedff",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Review Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Year of the performance review",
            "formatString": "0",
            "lineageTag": "b27f7c8c-1cd3-4f02-93ba-f6ef8bdaa15e",
            "sourceColumn": "Performance Review Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Rating assigned during performance review year",
            "formatString": "0",
            "lineageTag": "cad0f049-016b-4850-a7a9-ffc056549799",
            "sourceColumn": "Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Projects Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Number of projects completed by the employee in the review period",
            "formatString": "0",
            "lineageTag": "ecb0757f-0df0-4970-8869-2402464b0008",
            "sourceColumn": "Projects Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Project Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Number of projects the employee was expected to complete",
            "formatString": "0",
            "lineageTag": "8aa3d0ce-c892-4454-98e1-9263768c8421",
            "sourceColumn": "Project Target",
            "summarizeBy": "sum"
          },
          {
            "name": "Working Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Total working hours for the employee in the review period",
            "formatString": "0",
            "lineageTag": "87828cb7-50e1-48fd-8073-dcf2b09c8a1d",
            "sourceColumn": "Working Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Overtime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Total overtime hours worked in the review year",
            "formatString": "0",
            "lineageTag": "83ab7b9a-2adb-4305-addb-110639717899",
            "sourceColumn": "Overtime",
            "summarizeBy": "sum"
          },
          {
            "name": "Team Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Number of team members the employee worked with or led",
            "formatString": "0",
            "lineageTag": "3d03a84c-66f7-4456-b7b4-cf0c11e7a569",
            "sourceColumn": "Team Size",
            "summarizeBy": "sum"
          },
          {
            "name": "Potential Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Assessment of the employees potential for growth or promotion",
            "lineageTag": "c31478dd-15ec-4a57-8a8f-3e519e35f05e",
            "sourceColumn": "Potential Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Satisfaction Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Employee satisfaction level on a scale of 1 to 5",
            "formatString": "0",
            "lineageTag": "2b1fae8d-ba59-494b-80c6-b02c05a42633",
            "sourceColumn": "Satisfaction Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Incentive Amount ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": "Yearly incentive earned by the employee",
            "lineageTag": "45b1a3a5-8323-4223-a8b5-27e0de3edf4d",
            "sourceColumn": "Incentive Amount ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Bonus ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": "Yearly bonus earned by the employee",
            "lineageTag": "0f008646-be5e-4cac-87eb-31fdc394adc2",
            "sourceColumn": "Bonus ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af1e8ead-d6df-4243-bffd-2656d0c92b57",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "daefe653-4dbd-4cff-818a-b13040e6f3d4",
        "partitions": [
          {
            "name": "fact_performance",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Employee ID\"}, dim_employee, {\"Employee ID\"}, \"dim_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_employee\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dim_employee\", {\"Full Name\"}, {\"dim_employee.Full Name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded dim_employee\",{{\"dim_employee.Full Name\", \"Full Name\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Reordered Columns\", {\"Employee ID\"}, fact_employee, {\"Employee ID\"}, \"fact_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded fact_employee\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"fact_employee\", {\"Job Title\"}, {\"fact_employee.Job Title\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded fact_employee\",{{\"fact_employee.Job Title\", \"Job Title\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Employee ID\", \"Full Name\", \"Job Title\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"Job Title\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"Extra PRoject\", each if[Projects Handled]>[Project Target] then \"Exceeds Target\" else \"On Target\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Extra PRoject\", type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Extra PRoject\", \"Extra Project\"}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Extra Project\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns2\", each true),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Extra Project\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_resignationReason",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Resignation Reason ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each resignation reason",
            "formatString": "0",
            "lineageTag": "7c350945-0da4-48e3-b372-f88002535f2a",
            "sourceColumn": "Resignation Reason ID",
            "summarizeBy": "none"
          },
          {
            "name": "Reason Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Description of the resignation reason",
            "lineageTag": "2fac942f-53ba-43c4-8a80-73d9c6cda13a",
            "sourceColumn": "Reason Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e2d9ba2-9896-4b4d-9c44-d2c1150f3ef0",
        "partitions": [
          {
            "name": "dim_resignationReason",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\resignation_reason.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Resignation Reason ID\", Int64.Type}, {\"Reason Description\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_resigned",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each employee",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "613cd323-c0ce-4c77-90ef-b782d9ae08d4",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resignation Reason ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each resignation reason",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "79f82322-1be1-4786-baab-afd831fdaaea",
            "sourceColumn": "Resignation Reason ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resigned Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Date the employee resigned",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "69fed67f-12e4-47a1-ab39-60a473e8ca6f",
            "sourceColumn": "Resigned Date",
            "summarizeBy": "none"
          },
          {
            "name": "Resigned Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Type of resignation",
            "lineageTag": "f38bf0cb-f921-46c3-9f29-17abc04d3452",
            "sourceColumn": "Resigned Type",
            "summarizeBy": "none"
          },
          {
            "name": "Work Environment Feedback",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Feedback on work environment",
            "lineageTag": "020d871b-3232-4b97-a35c-e13d5f5b2d93",
            "sourceColumn": "Work Environment Feedback",
            "summarizeBy": "none"
          },
          {
            "name": "Management/Team Experience Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Experience with Management/Team score with 1 to 5",
            "formatString": "0",
            "lineageTag": "e23a9b56-8c2d-4b79-a628-9a393f3f9bef",
            "sourceColumn": "Management/Team Experience Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Level at Exit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Employees job role and organization level at the time of resignation",
            "lineageTag": "95937524-4124-49d7-b943-159caf8d5270",
            "sourceColumn": "Level at Exit",
            "summarizeBy": "none"
          },
          {
            "name": "Years at Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "(    fact_resigned[Resigned Date]-RELATED(fact_employee[Hire Date])",
              ")/365"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "eed520cf-d986-4bde-8fa6-5c0574bf737b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tenure Banding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    fact_resigned[Years at Company] <= 2, \"Less than 3\",",
              "    fact_resigned[Years at Company] <= 5, \"3-5\",",
              "    fact_resigned[Years at Company] <= 7, \"5-7\",",
              "    \"Above 7\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "faa1f5b7-f0ce-48d8-b566-33f71bc1cc0d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e4107b65-c226-4c19-8d5e-3dec769a38c0",
        "partitions": [
          {
            "name": "fact_resigned",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\resigned_table.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Resigned Date\", type date}, {\"Resigned Type\", type text}, {\"Resigned Reason\", type text}, {\"Work Environment Feedback\", type text}, {\"Management/Team Experience Score\", Int64.Type}, {\"Level at Exit\", type text}, {\"Resignation Reason ID\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Resigned Reason\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"Employee ID\", \"Resignation Reason ID\", \"Resigned Date\", \"Resigned Type\", \"Work Environment Feedback\", \"Management/Team Experience Score\", \"Level at Exit\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_training",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each employee",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1ad5fc14-3d08-4134-9013-b02ee289357a",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Training Session ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "References Dim_Training_Session, identifies the training session",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8494885d-f837-4819-853c-5438c9016acc",
            "sourceColumn": "Training Session ID",
            "summarizeBy": "none"
          },
          {
            "name": "Training Completion Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": "Date training was completed",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "b6be5361-b33f-4093-b8d4-c7cd9f5605d2",
            "sourceColumn": "Training Completion Date",
            "summarizeBy": "none"
          },
          {
            "name": "Certification Achieved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "description": "Indicates if certification was achieved post-training",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8b95a351-f835-40b2-ae7c-7897b64a3b46",
            "sourceColumn": "Certification Achieved",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "65e70b9a-9f86-4935-b8a0-a5792cdf5d60",
        "partitions": [
          {
            "name": "fact_training",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\training_development.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Training Session ID\", Int64.Type}, {\"Training Completion Date\", type date}, {\"Certification Achieved\", type logical}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"Training Completion Date\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_trainingSession",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Training Session ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Unique identifier for each training session",
            "formatString": "0",
            "lineageTag": "6ad976b1-5390-4770-920c-a0641d239716",
            "sourceColumn": "Training Session ID",
            "summarizeBy": "none"
          },
          {
            "name": "Training Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Name of the training session",
            "lineageTag": "fa05709d-54f2-4e6d-880b-6927b0f2fa53",
            "sourceColumn": "Training Name",
            "summarizeBy": "none"
          },
          {
            "name": "Training Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Type of training",
            "lineageTag": "deb3c9ca-0f1a-4b58-8086-057aa9362fb1",
            "sourceColumn": "Training Type",
            "summarizeBy": "none"
          },
          {
            "name": "Duration Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "Duration of the training session in hours",
            "formatString": "0",
            "lineageTag": "eca1799a-9ff9-455d-ba1f-cb3ea83dca88",
            "sourceColumn": "Duration Hours",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f50332de-e497-4b96-b6a1-28823abf69d9",
        "partitions": [
          {
            "name": "dim_trainingSession",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\training_session.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Training Session ID\", Int64.Type}, {\"Training Name\", type text}, {\"Training Type\", type text}, {\"Duration Hours\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_employee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e3b28e2-166d-4b18-8862-9d88add70bc0",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6975e44-1f66-493a-8ac1-32b64358926c",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "850f4014-e32c-4a1a-a6b2-b9a73551b230",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abff0abe-7fd8-4e23-ba1a-8d493cd8f074",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Education Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed246723-7f75-4e00-afe5-e3513b623e58",
            "sourceColumn": "Education Level",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34ec3ef-b5cd-429a-a729-672ce04f6232",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Ethnicity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecaf7422-9acc-4a63-bc5c-64bb47b23864",
            "sourceColumn": "Ethnicity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "17b58dde-a5cd-4358-a7cf-80afe5bb402e",
        "partitions": [
          {
            "name": "dim_employee",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_employee,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Employee ID\", \"Full Name\", \"Date of Birth\", \"Gender\", \"Education Level\", \"Region\", \"Country\", \"Latitude\", \"Longitude\", \"Ethnicity\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Other Columns\",{\"Region\", \"Latitude\", \"Longitude\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Employee ID\"}),",
                "    #\"Extracted Month Name\" = Table.TransformColumns(#\"Removed Duplicates\", {{\"Date of Birth\", each Date.MonthName(_), type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Extracted Month Name\",{{\"Date of Birth\", \"Month Name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_location",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddeeceeb-1c87-4a36-9856-d92c61eedf90",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "852c8f87-fbd9-4f76-9bd2-56911690fbec",
            "sourceColumn": "Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3e23b30-69d3-47f8-9152-679ca3b59994",
            "sourceColumn": "Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae5b8e9c-828a-4e11-a9ca-14ad140ce149",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "da0152a7-7864-45be-a65e-896f2fb909e5",
        "partitions": [
          {
            "name": "dim_location",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_employee,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Region\", \"Country\", \"Latitude\", \"Longitude\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"Country\", \"Latitude\", \"Longitude\", \"Region\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_department",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ba3a342-9c00-49c8-9bfc-4eb20d9ae7a1",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c3f47ab2-8172-4af8-be4f-bb5e2174ab1d",
        "partitions": [
          {
            "name": "dim_department",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_employee,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Department\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_jobtitle",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1184e8ce-fd2c-4c25-a1f2-800496efddee",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "Organization Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb572ccd-c79c-489d-bdac-de202fcfaffb",
            "sourceColumn": "Organization Level",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "80c626fc-bd47-43e1-8ded-26e9380e64fa",
        "partitions": [
          {
            "name": "dim_jobtitle",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_employee,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Job Title\", \"Organization Level\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_leaveReason",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Leave Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adfef3d4-e539-4c93-bd51-d0ced64e475f",
            "sourceColumn": "Leave Details",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e21939e8-df7f-442b-8be1-d2d4240124ce",
        "partitions": [
          {
            "name": "dim_leaveReason",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_leave,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Leave Details\", \"Leave Type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Other Columns\",{\"Leave Type\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_leaveType",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Leave Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68e4201a-8858-44ed-a564-c7fd7d5f95fb",
            "sourceColumn": "Leave Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7bd7c101-5aa8-4a2a-973a-1ca83d7c99f0",
        "partitions": [
          {
            "name": "dim_leaveType",
            "mode": "import",
            "queryGroup": "Data\\dim tables",
            "source": {
              "expression": [
                "let",
                "    Source = fact_leave,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Leave Type\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "154f7a1e-40bc-4cd1-b1fa-f36af8196450",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "190317e3-fe94-4541-90ca-419bf13f44ac",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3cab65de-d7ef-4ac1-a59d-dba2c01e4e6e",
            "sourceColumn": "QuarterOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8932e86b-b978-4205-833a-1329434be3da",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2137671-89e9-4d02-a02b-1025c20dfe99",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9cc00f-7249-4d94-9b40-b3c45e81e2e6",
            "sourceColumn": "DateInt",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8af9b0ef-d252-4d3b-b8e5-1f69b457a51c",
            "sortByColumn": "MonthOfYear",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthInCalendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f1648f4-80ad-46cd-9f4e-7358de6027e0",
            "sortByColumn": "MonthnYear",
            "sourceColumn": "MonthInCalendar",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterInCalendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1086e5c3-0c51-492d-9e1c-544c15a78f4b",
            "sourceColumn": "QuarterInCalendar",
            "summarizeBy": "none"
          },
          {
            "name": "DayInWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ae331cf9-a52d-4fa6-9a2e-ed88307f4a09",
            "sourceColumn": "DayInWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "85ad7232-8e43-45bf-80ab-7d59459156d0",
            "sortByColumn": "DayInWeek",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "WeekEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5752bda7-f83b-4ef8-826f-db6bf19bac97",
            "sourceColumn": "WeekEnding",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef8005cd-8af1-4a1d-b407-4a0c0d14ee59",
            "sourceColumn": "Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a91ad3ab-252f-415f-be4f-d685fc233b06",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "226f253c-9923-416f-b18a-11ffeef71779",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "ShortYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb56afe3-a8fb-462d-83bb-943d7e98f18c",
            "sourceColumn": "ShortYear",
            "summarizeBy": "none"
          },
          {
            "name": "FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77729fe7-78e1-40c8-9a39-aae381d7f384",
            "sourceColumn": "FY",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Year Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "df95ae7a-3bd2-487f-8636-239a7582c81c",
                "ordinal": 0
              },
              {
                "name": "QuarterInCalendar",
                "column": "QuarterInCalendar",
                "lineageTag": "4ed4cc7b-c9ee-4c17-a470-485380a4013a",
                "ordinal": 1
              },
              {
                "name": "MonthInCalendar",
                "column": "MonthInCalendar",
                "lineageTag": "8d8c9198-3bb3-4b47-9885-e4e819337b30",
                "ordinal": 2
              },
              {
                "name": "DayOfMonth",
                "column": "DayOfMonth",
                "lineageTag": "23a85637-86b0-444d-acfd-823c78fc6321",
                "ordinal": 3
              }
            ],
            "lineageTag": "316e71f2-41eb-44b6-bc9d-976347178aa6"
          }
        ],
        "lineageTag": "afc9da10-b4d1-40a7-b953-63256aeaaca5",
        "partitions": [
          {
            "name": "date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Date Parameter\"(#date(1958, 1, 1), #date(2026, 12, 31), 1),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "datadictionary",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5b392eb551e94a7d8084de78396d0ef0"
          }
        ],
        "columns": [
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0831145d-409a-4519-bbf2-fe1d15e0b0e3",
            "sourceColumn": "[Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "675968e6-2f8b-4408-8b10-db94803710d8",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b354e208-05cf-4566-aef9-c8a6d9254b5b",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d8a648ae-0feb-42a6-968f-0b20658df089",
            "sourceColumn": "[Location]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expressione",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "287ae3d4-4bf1-47b0-8690-de0dea82ff4a",
            "sourceColumn": "[Expressione]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "65e67454-17d0-4ce6-b158-4d079c4081bd",
        "partitions": [
          {
            "name": "datadictionary",
            "mode": "import",
            "source": {
              "expression": [
                "SELECTCOLUMNS(",
                "    FILTER(",
                "        INFO.VIEW.COLUMNS(),",
                "        [Table] <> \"Data Dictionary\" && NOT([IsHidden])",
                "    ),",
                "    \"Type\", \"Column\",",
                "    \"Name\", [Name],",
                "    \"Description\", [Description],",
                "    \"Location\", [Table],",
                "    \"Expressione\", [Expression]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "1919ba0b-d570-4037-82be-76d2c015881f",
        "measures": [
          {
            "name": "# of Employee",
            "displayFolder": "Diversity",
            "expression": "COUNTROWS(fact_employee)",
            "formatString": "0",
            "lineageTag": "9870eb51-35fb-4b39-9840-2c0837313005"
          },
          {
            "name": "# of Active Employees",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "COUNTROWS(",
              "    FILTER(fact_employee, ",
              "           fact_employee[Current Employment Status]=\"Active\")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e8373169-50ef-4d74-9667-691d447c048f"
          },
          {
            "name": "# of Female",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    [Cumulative Employee Count],",
              "    fact_employee[Gender]=\"Female\")"
            ],
            "formatString": "0",
            "lineageTag": "506a76a0-5f3f-4291-87ec-4b28b5f688dd"
          },
          {
            "name": "# of Male",
            "displayFolder": "Diversity",
            "expression": [
              "CALCULATE(",
              "    [Cumulative Employee Count],",
              "    fact_employee[Gender]=\"Male\")"
            ],
            "formatString": "0",
            "lineageTag": "926be376-df37-48f0-8df5-15d7db0c829a"
          },
          {
            "name": "# of Other",
            "displayFolder": "Diversity",
            "expression": [
              "CALCULATE(",
              "    [Cumulative Employee Count],",
              "    fact_employee[Gender]=\"Other\")"
            ],
            "formatString": "0",
            "lineageTag": "dacf613e-76b6-4526-9827-c849c6617c4f"
          },
          {
            "name": "%Female",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "DIVIDE([# of Female], [Cumulative Employee Count],0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "209be2b2-f63e-4b3a-b492-ba463925effa"
          },
          {
            "name": "%Male",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "DIVIDE([# of Male], [Cumulative Employee Count],0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bbb8b413-088e-4fab-8edb-4c80170b00e9"
          },
          {
            "name": "# of Resignation",
            "description": "No of total Resignation",
            "displayFolder": "Resigned",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    FILTER(",
              "        fact_resigned,",
              "        fact_resigned[Employee ID]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "981b2ca8-d485-4fa9-b8e6-a92d8fb1ea49"
          },
          {
            "name": "# of Voluntary Resignation",
            "description": "No of total Voluntary Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    FILTER(",
              "        fact_resigned,",
              "        fact_resigned[Resigned Type] = \"Voluntary\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d7dde708-1d10-4eaf-8d13-525fa442e096"
          },
          {
            "name": "# of Involuntary Resignation",
            "description": "No of total involuntary Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    FILTER(",
              "        fact_resigned,",
              "        fact_resigned[Resigned Type] = \"Involuntary\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c1efdaba-db69-4d67-952c-5c7b216ba352"
          },
          {
            "name": "# of First Year Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "CALCULATE(",
              "    [# of Resignation],",
              "    FILTER(",
              "        fact_resigned,",
              "        DATEDIFF(",
              "            RELATED(fact_employee[Hire Date]),",
              "            fact_resigned[Resigned Date],",
              "            YEAR",
              "        ) <= 1",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "11c7d296-4291-44ff-a64a-4ca7673dcd4f"
          },
          {
            "name": "% Voluntary Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": "DIVIDE([# of Voluntary Resignation], [# of Resignation],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "21c09dcd-e770-4cdb-b271-984afb91d2a8"
          },
          {
            "name": "% Involuntary Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": "DIVIDE([# of Involuntary Resignation], [# of Resignation],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1cc5baec-64cc-41e3-9afe-6d02b3c759f2"
          },
          {
            "name": "% First Year Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": "DIVIDE([# of First Year Resignation], [# of Resignation],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a7cb0e4c-737e-4b50-9d5a-d88fa1bc5202"
          },
          {
            "name": "# of Resignation by Reason",
            "displayFolder": "Resigned\\resigned profile\\reason bar chart",
            "expression": [
              "",
              "COUNTROWS(fact_resigned)"
            ],
            "formatString": "0",
            "lineageTag": "0235a7e8-5ed8-4152-8f5e-a2013616d94c"
          },
          {
            "name": "Labels PlaceHolders",
            "displayFolder": "Resigned\\resigned profile\\reason bar chart",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "51e6c791-6ce0-452d-80da-e8f66f0bebad"
          },
          {
            "name": "Label Bar Chart- Resignation Reason",
            "displayFolder": "Resigned\\resigned profile\\reason bar chart",
            "expression": [
              "",
              "SELECTEDVALUE(dim_resignationReason[Reason Description])"
            ],
            "lineageTag": "e2065e24-dd1f-473e-82a3-595d70dd506c"
          },
          {
            "name": "Avg Resignation Per Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "VAR _Resignation= [# of Resignation]",
              "Var _MonthCount=",
              "DATEDIFF(",
              "    Date( 2018,1,1),",
              "    TODAY(),",
              "    MONTH",
              ") +1",
              "RETURN",
              "DIVIDE(",
              "    _Resignation,",
              "    _MonthCount,",
              "    0",
              ")"
            ],
            "lineageTag": "be15f5ee-d5a7-4d92-a132-12d6ef44420c"
          },
          {
            "name": "Avg Time to Resign (Years)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "AVERAGEX(",
              "    fact_resigned,",
              "    DATEDIFF(",
              "        RELATED(fact_employee[Hire Date]),",
              "        fact_resigned[Resigned Date],",
              "        YEAR",
              "    )",
              ")"
            ],
            "lineageTag": "cf383107-93c3-4f03-873c-3d2373129167"
          },
          {
            "name": "#male",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": "[# of Male]*-1",
            "formatString": "0",
            "lineageTag": "d1f3c617-be48-47e0-96a7-2c4f7758351b"
          },
          {
            "name": "#female",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": "[# of Female]*-1",
            "formatString": "0",
            "lineageTag": "95daf59e-58c7-4b41-b1f0-3ce358895b7e"
          },
          {
            "name": "# of Resignation PY",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "CALCULATE(",
              "    [# of Resignation],",
              "    DATEADD('date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "79ed1f5d-a625-4536-b5c7-dd9bd2a8fec7"
          },
          {
            "name": "# of Resignation CY",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "CALCULATE(",
              "    [# of Resignation],",
              "    YEAR(fact_resigned[Resigned Date]) = SELECTEDVALUE('date'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b90eb4a3-8b7b-4391-beba-fe8ba891829b"
          },
          {
            "name": "New Hires",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": "COUNTROWS(fact_employee)",
            "formatString": "0",
            "lineageTag": "924cfdee-8c95-4737-8951-a2063265c345"
          },
          {
            "name": "Overall Attrition Rate",
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "DIVIDE(",
              "    [# of Resignation], ",
              "    [# of Employee], ",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2f02b0a0-f0ec-46ad-bed8-9b4ad0969652"
          },
          {
            "name": "Voluntary Attrition Rate",
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "DIVIDE(",
              "    [# of Voluntary Resignation],",
              "    [# of Employee],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7cf070bb-d849-4dff-b902-9d098c918b44"
          },
          {
            "name": "Involuntary Attrition Rate",
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "DIVIDE(",
              "    [# of Involuntary Resignation],",
              "    [# of Employee],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "df55039d-15aa-4c59-826f-09a5ca3f380e"
          },
          {
            "name": "Ethnicity Count",
            "expression": "COUNTROWS(fact_employee)",
            "formatString": "0",
            "lineageTag": "bcf08fb4-80d4-4f49-9411-cca7f800042e"
          },
          {
            "name": "Hires",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fact_employee[Employee ID]),",
              "    fact_employee[Hire Date] >= MIN('Date'[Date]),",
              "    fact_employee[Hire Date] <= MAX('Date'[Date])",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "30425783-3171-485d-99ea-822a02d149ce"
          },
          {
            "name": "Terminations",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fact_employee[Employee ID]),",
              "    fact_employee[Current Employment Status] = \"Resigned\" || ",
              "    fact_employee[Current Employment Status] = \"Terminated\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "245c7528-abf1-4a2b-9424-f2e06c8be702"
          },
          {
            "name": "Net Change in Headcount",
            "expression": [
              "",
              "[Hires] - [Terminations]",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3085b68f-6b86-480b-8af2-e0672147aff8"
          },
          {
            "name": "Overtime Headcount",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(fact_performance[Employee ID]),",
              "    fact_performance[Overtime] > 0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0a1239a6-0b9f-45a8-96d6-ff524acb60d6"
          },
          {
            "name": "Resignation Rate by Age Band",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "CALCULATE([Overall Attrition Rate], ",
              "    GROUPBY(fact_employee, fact_employee[Age Band]))",
              ""
            ],
            "lineageTag": "c9b73368-e6d2-4895-983d-595301f97f7d"
          },
          {
            "name": "Very High Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"Very High\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "93de24d2-2e23-49d5-903a-6134db67390b"
          },
          {
            "name": "High Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"High\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "69d23417-fc81-4d0d-b70f-3d2326604d4d"
          },
          {
            "name": "Moderate Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"Moderate\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "29ea97dd-0d88-420d-818a-a762b1b197ef"
          },
          {
            "name": "Very Low Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"Very Low\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "17789e82-490d-4f9c-847d-c52e7af0bc47"
          },
          {
            "name": "Average Training Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Training",
            "expression": [
              "",
              "AVERAGE(dim_trainingSession[Duration Hours])"
            ],
            "lineageTag": "17feb73f-1034-46f1-8a87-684717b631c9"
          },
          {
            "name": "Completed Trainings",
            "displayFolder": "Training",
            "expression": [
              "",
              "CALCULATE(",
              "COUNTROWS(fact_training),",
              "fact_training[Certification Achieved] = TRUE()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "69c64ba4-e155-45d4-94ec-707974c2bc41"
          },
          {
            "name": "Total Employees Trained",
            "displayFolder": "Training",
            "expression": "DISTINCTCOUNT(fact_training[Employee ID])",
            "formatString": "0",
            "lineageTag": "1addf775-feca-43c0-add2-74ab350c3a2a"
          },
          {
            "name": "Total Training Hours",
            "displayFolder": "Training",
            "expression": [
              "",
              "SUMX(",
              "fact_training, ",
              "RELATED(dim_trainingSession[Duration Hours])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "94aab7a7-a4fa-4046-a133-fd8231e2b429"
          },
          {
            "name": "Total Training Sessions Completed",
            "displayFolder": "Training",
            "expression": [
              "",
              "CALCULATE(",
              "COUNT(fact_training[Training Session ID]),",
              "fact_training[Certification Achieved] = TRUE()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5621fe5d-e4b1-4f8d-a1ef-085bdd114ca4"
          },
          {
            "name": "Training Completion Rate",
            "displayFolder": "Training",
            "expression": [
              "",
              "DIVIDE(",
              "[Total Training Sessions Completed], ",
              "COUNT(fact_training[Training Session ID]),",
              "0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b914eb26-333a-47ea-85c5-5c46a584ebbd"
          },
          {
            "name": "Skill Gap Percentage",
            "displayFolder": "Training",
            "expression": [
              "",
              "DIVIDE(",
              "    DISTINCTCOUNT(fact_training[Employee ID]) - ",
              "    CALCULATE(DISTINCTCOUNT(fact_training[Employee ID]), fact_training[Certification Achieved] = TRUE()),",
              "    DISTINCTCOUNT(fact_training[Employee ID]),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f88d1c55-702d-49fb-a306-684d7b447c0a"
          },
          {
            "name": "Slope",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR AvgX = AVERAGEX(ALL(fact_employee[Tenure]), fact_employee[Tenure])",
              "VAR AvgY = AVERAGEX(ALL(fact_employee[Tenure]), [#female])",
              "VAR Numerator = ",
              "    SUMX(",
              "        ALL(fact_employee[Tenure]),",
              "        (fact_employee[Tenure] - AvgX) * ([%Female] - AvgY)",
              "    )",
              "VAR Denominator = ",
              "    SUMX(",
              "        ALL(fact_employee[Tenure]),",
              "        (fact_employee[Tenure] - AvgX) ^ 2",
              "    )",
              "RETURN",
              "DIVIDE(Numerator, Denominator, 0)",
              ""
            ],
            "lineageTag": "10d598e3-1fe5-4868-8162-b99f49a70123"
          },
          {
            "name": "Intercept",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR AvgX = AVERAGEX(ALL(fact_employee[Tenure]), fact_employee[Tenure])",
              "VAR AvgY = AVERAGEX(ALL(fact_employee[Tenure]), [%Female])",
              "VAR SlopeValue = [Slope]",
              "RETURN",
              "AvgY - (SlopeValue * AvgX)",
              ""
            ],
            "lineageTag": "d2aabcf3-afed-4b66-b8d0-1e96560320a1"
          },
          {
            "name": "predicted %Female_2024",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR SlopeValue = [Slope]",
              "VAR InterceptValue = [Intercept]",
              "RETURN",
              "InterceptValue + (SlopeValue * 2024)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7cd6b813-001e-42b3-a8bd-0dc6801e3b20"
          },
          {
            "name": "predicted % Female_2025",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR SlopeValue = [Slope]",
              "VAR InterceptValue = [Intercept]",
              "RETURN",
              "InterceptValue + (SlopeValue * 2025)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1661498d-77cb-4e34-9219-7e51f28bb6d1"
          },
          {
            "name": "High-Falling Short",
            "description": "Number 7 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")",
            "formatString": "0",
            "lineageTag": "fa793b8d-212c-4ba8-8a7c-0f8ca40f9205"
          },
          {
            "name": "High-On Track",
            "description": "Number 8 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")",
            "formatString": "0",
            "lineageTag": "5e4a9671-6ca0-4cf2-93c2-e42d122f5daf"
          },
          {
            "name": "High-Peak Performer",
            "description": "Number 9 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\")",
            "formatString": "0",
            "lineageTag": "5a8361df-9a27-4581-9f0f-2214fe0abc4f"
          },
          {
            "name": "Low-Falling Short",
            "description": "Number 1 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")",
            "formatString": "0",
            "lineageTag": "d1e8fb4c-efe0-45e7-b6ad-697211580ec2"
          },
          {
            "name": "Low-On Track",
            "description": "Number 2 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")",
            "formatString": "0",
            "lineageTag": "561128da-a5c8-4b9a-8373-e77c23a492a2"
          },
          {
            "name": "Low-Peak Performer",
            "description": "Number 3 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")",
            "formatString": "0",
            "lineageTag": "8c64d53f-0e5e-4ce2-8dd5-3df1aaeb2219"
          },
          {
            "name": "Moderate-Falling Short",
            "description": "Number 4 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")",
            "formatString": "0",
            "lineageTag": "0f15d2d0-ee5a-405f-b0be-003cd288e41f"
          },
          {
            "name": "Moderate-On Track",
            "description": "Number 5 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")",
            "formatString": "0",
            "lineageTag": "45f40164-d478-4bc9-936a-611782eef382"
          },
          {
            "name": "Moderate-Peak Performer",
            "description": "Number 6 box",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")",
            "formatString": "0",
            "lineageTag": "798bef83-3af2-4594-a831-401ca7eb5e6d"
          },
          {
            "name": "9-Box Distinct ID",
            "description": "Total of all category (distinct count)",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\")",
            "formatString": "0",
            "lineageTag": "73f6ce79-22e7-44df-928a-00708aa6a7aa"
          },
          {
            "name": "Promotion",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    fact_employee[Times Promoted]>=1",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3d324027-6d51-441b-8315-7c38402c89e0"
          },
          {
            "name": "Never_Promoted",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    fact_employee[Times Promoted]=0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2be8d0d9-8801-4380-a9f7-6b3f1e2432be"
          },
          {
            "name": "Rolling 12-Month Hires",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    DATESINPERIOD(",
              "        'Date'[Date],",
              "        MAX('Date'[Date]),",
              "        -12,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a426bfa8-99b4-4e5d-a9bf-1981bbc21e59"
          },
          {
            "name": "Headcount 12 Months Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    DATESINPERIOD(",
              "        'Date'[Date],",
              "        MAX('Date'[Date]),",
              "        -12,",
              "        MONTH",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cef52d53-5daf-41b3-a3e4-0d386373b08a"
          },
          {
            "name": "Rolling 12-Month Terminations",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_resigned),",
              "    DATESINPERIOD(",
              "        'Date'[Date], -- Use the Date column from your Date table",
              "        MAX('Date'[Date]),",
              "        -12,",
              "        MONTH",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a91ab0f3-67af-451d-868e-53de1bdfd5bc"
          },
          {
            "name": "Attrition Rate (Rolling 12 Months)",
            "expression": [
              "",
              "DIVIDE(",
              "    [Rolling 12-Month Terminations],",
              "    [Headcount 12 Months Ago],",
              "    0",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "831f34a3-1615-4ecf-9794-8075683ba7f0"
          },
          {
            "name": "Proportion of Employees by Organization Level",
            "expression": [
              "",
              "DIVIDE(",
              "    COUNT(fact_employee[Employee ID]),",
              "    CALCULATE(",
              "        COUNT(fact_employee[Employee ID]),",
              "        ALL(fact_employee[Organization Level])",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f22fbc84-7933-498c-830b-beda6da451f9"
          },
          {
            "name": "Total Distinct Employee ID",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT('9-Box Grid'[Employee ID]),ALL())",
            "formatString": "0",
            "lineageTag": "30c54bf0-3849-46d2-8571-8622bcaa04a7"
          },
          {
            "name": "% Low-Falling Short",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5f14fcac-d43d-42a9-bf4a-f3b631568447"
          },
          {
            "name": "% Low-On Track",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3d77488a-04af-4710-a159-394fbb0f32b6"
          },
          {
            "name": "% Low-Peak Performer",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "257e6f95-447c-4205-b84c-c19749a764a3"
          },
          {
            "name": "% Moderate-Falling Short",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a4374ef0-d2dd-4099-86fd-9d67bfda7be7"
          },
          {
            "name": "% Moderate-On Track",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ad2eb833-c771-42ff-93f1-22f92b64e472"
          },
          {
            "name": "% Moderate-Peak Performer",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7da70162-fc7e-433c-8798-03f416d2c8da"
          },
          {
            "name": "% High-Falling Short",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "095c1248-2da6-482c-93b0-03762b08cdf9"
          },
          {
            "name": "% High-On Track",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "633c7ffb-eb19-4d83-a317-677feb24a4a4"
          },
          {
            "name": "% High-Peak Performer",
            "displayFolder": "% 9-Box",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\")/[9-Box Distinct ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cd9adfba-5082-433e-8f02-f413d6de680e"
          },
          {
            "name": "% 9-Box Distinct ID",
            "displayFolder": "% 9-Box",
            "expression": "(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\"))/[Total Distinct Employee ID]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4aef3a58-3f53-4177-9881-2c7acab06258"
          },
          {
            "name": "Star Performer",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\")",
            "formatString": "0",
            "lineageTag": "fe1ca0c1-89c9-4daf-969d-19f95bbc065d"
          },
          {
            "name": "Developing Star",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")+ CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")",
            "formatString": "0",
            "lineageTag": "bbe2716c-d1a5-4417-8f6c-30c67b2b5eba"
          },
          {
            "name": "Needs Development",
            "displayFolder": "Distinct count of 9-Box & Total",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")+CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")",
            "formatString": "0",
            "lineageTag": "7aa3dc02-eaf7-4326-9762-7be8b4e55de8"
          },
          {
            "name": "% Star Performer",
            "displayFolder": "% 9-Box",
            "expression": "(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Peak Performer\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-On Track\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Peak Performer\")/[9-Box Distinct ID])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "40baf046-46f7-4b38-aac1-728a272392d0"
          },
          {
            "name": "% Developing Star",
            "displayFolder": "% 9-Box",
            "expression": "(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Peak Performer\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-On Track\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"High-Falling Short\")/[9-Box Distinct ID])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f100d91b-bf73-4fb7-9575-9845489ee131"
          },
          {
            "name": "% Needs Development",
            "displayFolder": "% 9-Box",
            "expression": "(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-Falling Short\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Low-On Track\")/[9-Box Distinct ID])+(CALCULATE(DISTINCTCOUNT(fact_performance[Employee ID]),'9-Box Grid'[9-Box Grid Category]=\"Moderate-Falling Short\")/[9-Box Distinct ID])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "77d6931f-f5c0-4248-ba41-9ca5cd4e0ed4"
          },
          {
            "name": "Distinct ID (Year)",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "DISTINCTCOUNT('Full All'[Employee ID])",
            "formatString": "0",
            "lineageTag": "5eafe119-dff2-4f13-9b84-6e0c4e13098e"
          },
          {
            "name": "Total Project Handled",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF(ISFILTERED('Full All'[Performance Review Year]),SUM('Full All'[Projects Handled]),CALCULATE(SUM('Full All'[Projects Handled]),'Full All'[Performance Review Year] = \"All\"))",
            "formatString": "0",
            "lineageTag": "c67d4340-b67b-4de8-b928-6daf5531283b"
          },
          {
            "name": "Total Project Targeted",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF(ISFILTERED('Full All'[Performance Review Year]),SUM('Full All'[Project Target]),CALCULATE(SUM('Full All'[Project Target]),'Full All'[Performance Review Year] = \"All\"))",
            "formatString": "0",
            "lineageTag": "f33eecc9-b17b-4191-9913-40f8c875c64a"
          },
          {
            "name": "% Total Completion (TC)",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "DIVIDE([Total Project Handled],[Total Project Targeted])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a830e95c-bb2e-47ca-95ad-59d9b46b2f47"
          },
          {
            "name": "Handled",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF(ISFILTERED('Full All'[Performance Review Year]), SUM('Full All'[Projects Handled]), SUM('Full All'[Projects Handled]) / 2)",
            "formatString": "0",
            "lineageTag": "b6e07127-bda6-4388-ae14-81db1ff9cebd"
          },
          {
            "name": "Targeted",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF(ISFILTERED('Full All'[Performance Review Year]), SUM('Full All'[Project Target]), SUM('Full All'[Project Target]) / 2)",
            "formatString": "0",
            "lineageTag": "7dbc87f2-319d-48a1-9639-dc266be6a855"
          },
          {
            "name": "Extra Project",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF([Handled]>[Targeted],\"Exceeds Target\", \"On Target\")",
            "lineageTag": "e44d5db8-501e-44d6-bd85-50d782a4ac68"
          },
          {
            "name": "Progress Percentage (PP)",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "DIVIDE([Handled],[Targeted])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b8ae9c96-a13d-42e7-b7de-16088489c2dd"
          },
          {
            "name": "Data Bars (PP)",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "DIVIDE([Handled],[Targeted])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "68b45057-30ce-4c65-aa30-699622f23d78"
          },
          {
            "name": "DisplayData (Distinct ID)",
            "displayFolder": "Project Handled, Targeted, and Percentage",
            "expression": "IF(ISFILTERED('Full All'[Performance Review Year]),DISTINCTCOUNT('Full All'[Employee ID]),CALCULATE(DISTINCTCOUNT('Full All'[Employee ID]),'Full All'[Performance Review Year] = \"All\"))",
            "formatString": "0",
            "lineageTag": "82e68d0d-eae7-4be8-86f2-339c298daf3a"
          },
          {
            "name": "Overall Max/Min linechart Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "VAR Resignation=  [# of Resignation]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Resignation]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Resignation]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "97f6562e-cc82-47f5-a5b9-e4e738fda4f8"
          },
          {
            "name": "Overall Max/Min linechart Vol Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "VAR Resignation=  [# of Voluntary Resignation]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Voluntary Resignation]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Voluntary Resignation]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "75f768df-79a4-4bf9-9299-fcb7cd3898d6"
          },
          {
            "name": "Overall Max/Min linechart invol Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "VAR Resignation=  [# of Involuntary Resignation]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Involuntary Resignation]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "    [# of Involuntary Resignation]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "f0e2056e-5f12-4e79-8d3c-22c99320c779"
          },
          {
            "name": "Overall Max/Min linechart 1st year Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "VAR Resignation=  [# of First Year Resignation]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "     [# of First Year Resignation]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "     [# of First Year Resignation]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "f5809f31-b1d8-49f4-90ae-62367907d4ac"
          },
          {
            "name": "Dynamic Bar Color",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "VAR SelectedField = SELECTEDVALUE('Dept-Org Lvl'[Dept-Org Lvl])  // Capture the selected field parameter",
              "VAR MaxResignation =",
              "    SWITCH(",
              "        SelectedField,",
              "        \"Department\",",
              "            MAXX(",
              "                SUMMARIZE(",
              "                    'dim_department',",
              "                    'dim_department'[Department]",
              "                    ",
              "                ),",
              "                [# of Resignation]",
              "            ),",
              "        \"Organization Level\",",
              "            MAXX(",
              "                SUMMARIZE(",
              "                    'dim_jobtitle',",
              "                    'dim_jobtitle'[Organization Level]",
              "                ),",
              "                [# of Resignation]",
              "            ),",
              "        BLANK()",
              "    )",
              "VAR Color =",
              "    IF(",
              "        [# of Resignation] = MaxResignation,",
              "        \"#751d84\",  // Highlight color for max resignation",
              "        \"#808080\"   // Default color for other bars",
              "    )",
              "RETURN",
              "    Color",
              ""
            ],
            "lineageTag": "cace0750-716b-4913-bdce-bb9ff8845a77"
          },
          {
            "name": "Max Resignation",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "Var MaxResignation=",
              "MAXX(",
              "    ALL('date'), ",
              "    [# of Resignation]",
              ")",
              "VAR Color=",
              "IF(",
              "    [# of Resignation]= MaxResignation, ",
              "    \"#751d84\",",
              "    \"#808080\"",
              ")",
              "",
              "RETURN",
              "Color"
            ],
            "lineageTag": "b80b047f-cfb2-4e8a-8d9a-8026fc46157a"
          },
          {
            "name": "SelectedDimension",
            "displayFolder": "Resigned\\resigned profile",
            "expression": [
              "",
              "SELECTEDVALUE('Dept-Org Lvl'[Dept-Org Lvl])"
            ],
            "lineageTag": "392218c5-cbbe-49e5-a5c4-560a5d92d690"
          },
          {
            "name": "Color Country",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Rank by Avg Time to Resign] = 1, \"#741d83\",        -- Blue for the highest value",
              "    [Rank by Avg Time to Resign] = 2, \"#741d83\",        -- Blue for the second-highest value",
              "    [Rank by Avg Time to Resign] > 2, \"#D3D3D3\",        -- Gray for all other values",
              "    \"#FFFF99\"                              -- Default white (optional)",
              ")"
            ],
            "lineageTag": "0a850cb9-8d39-433e-bf03-4fe3e5812535"
          },
          {
            "name": "Rank by Avg Time to Resign",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(fact_employee[Country]), -- Replace with your Country column",
              "    [Avg Time to Resign (Years)],",
              "    ,",
              "    DESC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b8afd693-5fc1-426c-9b31-ec28eff5276d"
          },
          {
            "name": "Rank by AgeBand",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "RANKX(",
              "    ALLSELECTED(fact_employee[Age Band]), -- Replace with your Country column",
              "    [Avg Time to Resign (Years)],",
              "    ,",
              "    DESC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b8efeae3-ff5b-49e5-9a4c-2dafe9d3d27d"
          },
          {
            "name": "Color Ageband",
            "displayFolder": "Resigned\\Resigned Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Rank by AgeBand] = 1, \"#741d83\",        -- Blue for the highest value",
              "    [Rank by AgeBand] = 2, \"#741d83\",        -- Blue for the second-highest value",
              "    [Rank by AgeBand] > 2, \"#D3D3D3\",        -- Gray for all other values",
              "    \"#FFFF99\"                              -- Default white (optional)",
              ")"
            ],
            "lineageTag": "b25663df-1c57-4204-ae4a-7662d39625aa"
          },
          {
            "name": "Low Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"Low\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c22dbaf4-68cb-4c62-83ce-03b096143b8a"
          },
          {
            "name": "Will not Resign Risk Employee",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Profile of Employee'),",
              "    'Profile of Employee'[AH. Resignation Probability Category]=\"Will not Resign\" && 'Profile of Employee'[T. Current Employment Status]= \"Active\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "32aa643c-3fcd-477b-adb4-5271f4443949"
          },
          {
            "name": "Avg Probability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": "AVERAGE('Profile of Employee'[AF. Resignation Probability])",
            "lineageTag": "e80d8f7b-93ba-4667-8a82-e393be59c639"
          },
          {
            "name": "Dynamic Color",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    MAX(resignation_prediction[Resignation Probability]) < 0.05, \"#44CE1B\",  -- Light Green",
              "    MAX(resignation_prediction[Resignation Probability]) <= 0.20, \"#BBDB44\", -- Green-Yellow",
              "    MAX(resignation_prediction[Resignation Probability]) <= 0.40, \"#F7E379\", -- Yellow",
              "    MAX(resignation_prediction[Resignation Probability]) <= 0.60, \"#F2A134\", -- Orange",
              "    MAX(resignation_prediction[Resignation Probability]) <= 0.80, \"#FF681E\", -- Red-Orange",
              "    \"#E51F1F\" -- Bright Red for > 0.80",
              ")"
            ],
            "lineageTag": "1af27032-103e-4a00-a4ab-8fb41193141f"
          },
          {
            "name": "Overall Max/Min linechart Invoulantry Attrition",
            "displayFolder": "Resigned\\Attrition Prediction",
            "expression": [
              "",
              "VAR Resignation=  [Involuntary Attrition Rate]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Involuntary Attrition Rate]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Involuntary Attrition Rate]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "070f825d-1716-4de5-9a57-7893ac6bfb01"
          },
          {
            "name": "Overall Max/Min linechart voulantry Attrition",
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "VAR Resignation=  [Voluntary Attrition Rate]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Voluntary Attrition Rate]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Voluntary Attrition Rate]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "9850aa4c-752c-4553-a65e-5fda2e786eeb"
          },
          {
            "name": "Overall Max/Min linechart Overll Attrition",
            "displayFolder": "Resigned\\Attrition Analysis",
            "expression": [
              "",
              "VAR Resignation=  [Overall Attrition Rate]",
              "Var MaxResignation= ",
              "MAXX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Overall Attrition Rate]",
              ")",
              "Var MinResignation= ",
              "MINX(",
              "    ALLSELECTED('date'[Year]),",
              "     [Overall Attrition Rate]",
              ")",
              "",
              "VAR Result=",
              "SWITCH(",
              "    TRUE(),",
              "    Resignation=MaxResignation, \"RED\",",
              "    Resignation=MinResignation, \"Green\",",
              "    \"#751d84\"",
              ")",
              "",
              "RETURN",
              "Result"
            ],
            "lineageTag": "a08c8504-424a-4e72-b34f-a064266a493c"
          },
          {
            "name": "Avg Tenure Female",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Tenure]),",
              "    dim_employee[Gender]=\"Female\"",
              ")"
            ],
            "lineageTag": "5c30778f-da46-4afd-be5f-7a911b75a4d3"
          },
          {
            "name": "Avg Tenure Male",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Tenure]),",
              "    dim_employee[Gender]=\"Male\"",
              ")"
            ],
            "lineageTag": "dfee2ba0-78f7-4be6-be87-001ca2cc9bb6"
          },
          {
            "name": "Avg Year Female",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Age]),",
              "    dim_employee[Gender]= \"Female\"",
              ")"
            ],
            "lineageTag": "4521953b-00a1-414a-abad-e33b2457b5b3"
          },
          {
            "name": "Avg Year Male",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Age]),",
              "    dim_employee[Gender]= \"Male\"",
              ")"
            ],
            "lineageTag": "717236cb-4bd7-478b-ab91-09f5ee628786"
          },
          {
            "name": "Avg Salary Female",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Base Salary ($)]),",
              "    dim_employee[Gender]= \"Female\"",
              ")"
            ],
            "lineageTag": "1180c948-eadb-4e68-a039-1750868a0ac8"
          },
          {
            "name": "Avg Salary Male",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Base Salary ($)]),",
              "    dim_employee[Gender]= \"Male\"",
              ")"
            ],
            "lineageTag": "8ccd2fa8-9a0b-40c8-863e-d13b474af72c"
          },
          {
            "name": "Avg Salary Other",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Base Salary ($)]),",
              "    dim_employee[Gender]= \"Other\"",
              ")"
            ],
            "lineageTag": "a8a7e4b5-db31-4969-ad47-5b77a3b109eb"
          },
          {
            "name": "Avg Year Other",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Age]),",
              "    dim_employee[Gender]= \"Other\"",
              ")"
            ],
            "lineageTag": "6043e82b-53f0-4ca8-8e80-514d770f0bf6"
          },
          {
            "name": "Avg Tenure Other",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(fact_employee[Tenure]),",
              "    dim_employee[Gender]=\"Other\"",
              ")"
            ],
            "lineageTag": "4d82d98a-4e08-468a-ad07-60b86c1c052f"
          },
          {
            "name": "Hires R12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR NumofMonths= 12",
              "VAR LastSelectedDate= MAX('date'[Date])",
              "VAR Period= DATESINPERIOD( 'date'[Date], LastSelectedDate, -NumofMonths, MONTH)",
              "VAR Result= ",
              "CALCULATE(",
              "    AVERAGEX(",
              "        VALUES('date'[MonthnYear]),",
              "        [Hires]",
              "    ),",
              "    Period",
              ")",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "97285b05-718a-4492-8e9f-44f3bde5bbb3"
          },
          {
            "name": "Attrition rate R12m",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": [
              "",
              "VAR NumofMonths= 12",
              "VAR LastSelectedDate= MAX('date'[Date])",
              "VAR Period= DATESINPERIOD( 'date'[Date], LastSelectedDate, -NumofMonths, MONTH)",
              "VAR Result= ",
              "CALCULATE(",
              "    AVERAGEX(",
              "        VALUES('date'[MonthnYear]),",
              "        [Overall Attrition Rate]",
              "    ),",
              "    Period",
              ")",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "30c3f85a-7b36-48c7-8180-96ad6db88b4c"
          },
          {
            "name": "Avg Age",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": "AVERAGE(fact_employee[Age])",
            "lineageTag": "6cec20f4-dd7a-4d83-b110-2c82c529325c"
          },
          {
            "name": "Avg Tenure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Diversity",
            "expression": "AVERAGE(fact_employee[Tenure])",
            "lineageTag": "48be54c3-9c76-4c5e-911f-2305fb416aa1"
          },
          {
            "name": "Cumulative Employee Count",
            "displayFolder": "Diversity",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(fact_employee),",
              "    FILTER(",
              "        ALL('date'),",
              "        'date'[Date] <= MAX('date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "179c6664-a5e2-40ab-aec2-3a39a2cd62f0"
          },
          {
            "name": "% of Others",
            "displayFolder": "Diversity",
            "expression": "DIVIDE([# of Other], [Cumulative Employee Count],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b589300f-4c38-4c12-b617-c03f740dde60"
          }
        ],
        "partitions": [
          {
            "name": "_measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Age-tenure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "52139b6251574fa0aaaec299797a81d5"
          }
        ],
        "columns": [
          {
            "name": "Age-Tenure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6d6360f9-86a2-472a-883f-5e160faaf987",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e8485c24-2e52-4711-ba64-d9ff858fc04e",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "130f0ddc-31ca-4f7b-86bf-da239093159c",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "86a858c1-9031-4875-8b3d-cf0023556ecf",
        "partitions": [
          {
            "name": "Age-tenure",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Age Banding\", NAMEOF('fact_employee'[Age Band]), 0),",
                "    (\"Tenure Banding\", NAMEOF('fact_resigned'[Tenure Banding]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dept-Org Lvl",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0a1971714bb24cd0ac2d470e78f16f66"
          }
        ],
        "columns": [
          {
            "name": "Dept-Org Lvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "685f17ef-f163-4327-9825-9fc2a271e8a1",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Dept-Org Lvl Fields"
                }
              ]
            },
            "sortByColumn": "Dept-Org Lvl Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dept-Org Lvl Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "617087ac-3c61-4a37-9638-19d3162181b9",
            "sortByColumn": "Dept-Org Lvl Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dept-Org Lvl Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d52b5867-a0fa-4c18-b532-7957a9da88d1",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "802f68c5-b81e-4bc2-8be3-4e1575985901",
        "partitions": [
          {
            "name": "Dept-Org Lvl",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Department\", NAMEOF('dim_department'[Department]), 0),",
                "    (\"Organization Level\", NAMEOF('dim_jobtitle'[Organization Level]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ViewMeasue",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4d27d9f8e4b84c86bbc869763c03149f"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c3b2334-0069-4fb0-8ed6-c9a59da30657",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c454386d-9c84-4a84-b500-55ea231c981d",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c0ef2dc-890d-4f45-9661-6ed5bff43fe5",
            "sourceColumn": "[Table]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0b30d92-72d6-4e2d-964e-75d5cfe62ebe",
            "sourceColumn": "[Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "edb6c3e8-c7c9-4636-bd95-16e5e7bd4854",
            "sourceColumn": "[DataType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "10c2f679-1faf-4bdd-8e34-546504090e55",
            "sourceColumn": "[Expression]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "03b3245e-b3e9-4285-8c34-e3c2a84597df",
            "sourceColumn": "[FormatString]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsHidden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aa300461-616c-4450-8464-ca5cf58497ca",
            "sourceColumn": "[IsHidden]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9c3a765f-65db-48a0-9344-93d96f51313e",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPIID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5d740eee-76f5-4299-b80a-e8d6d780348f",
            "sourceColumn": "[KPIID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsSimpleMeasure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ea763b12-d2b6-4910-995f-45630e25e3de",
            "sourceColumn": "[IsSimpleMeasure]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DisplayFolder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f05f22ca-ecfa-4972-84a2-737822a03723",
            "sourceColumn": "[DisplayFolder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DetailRowsDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c4fa21a-2d7a-4964-92db-26fd86c59317",
            "sourceColumn": "[DetailRowsDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DataCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "001ab594-5850-4662-8372-b6126f706c72",
            "sourceColumn": "[DataCategory]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FormatStringDefinition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4f08b39e-8578-49bb-9aae-c9f07b81a8dd",
            "sourceColumn": "[FormatStringDefinition]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LineageTag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ac3757bb-f4fe-4df3-9929-a747558df383",
            "sourceColumn": "[LineageTag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b1f0479f-0822-4a5d-9dde-b3392c528787",
        "partitions": [
          {
            "name": "ViewMeasue",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.MEASURES()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "View_Relation",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "54ec869afacd4eb89598458670e17f51"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "326209d0-1c8e-493f-80ef-45d0a3f98f01",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bef8e4d2-bf07-48bf-9b6b-a80f78b11240",
            "sourceColumn": "[Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Relationship",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ff819b3-f3f1-4686-8c1c-c9b574170dc9",
            "sourceColumn": "[Relationship]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "67c0b5d3-cb2f-4311-bfa3-63a4058854a7",
            "sourceColumn": "[Model]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "158e2bea-d2dc-4cd2-8c69-73d14674efa1",
            "sourceColumn": "[IsActive]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CrossFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "517658ac-4e7a-45f0-bd13-a008d1cb191e",
            "sourceColumn": "[CrossFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RelyOnReferentialIntegrity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fb098895-92e2-4985-a1b1-8e2691ce8cff",
            "sourceColumn": "[RelyOnReferentialIntegrity]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a8380b14-dc59-4ef1-8145-14d5b12622c6",
            "sourceColumn": "[FromTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "87faee15-71b3-46b8-8622-c6672921f8f2",
            "sourceColumn": "[FromColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FromCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2315c20f-bb56-4f90-9d27-fe2e92f2c2a3",
            "sourceColumn": "[FromCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToTable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fbf6a544-e9ff-4f1c-abb5-fd6012e1cafb",
            "sourceColumn": "[ToTable]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a3198e8c-15d5-43ca-aba1-67a4c62a3de4",
            "sourceColumn": "[ToColumn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ToCardinality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "825b3053-b666-430a-8b6f-955d83875bd5",
            "sourceColumn": "[ToCardinality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "759be33e-11fe-4afd-8dce-f3a30cb43f5a",
            "sourceColumn": "[State]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SecurityFilteringBehavior",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "938cc7d8-ff4f-48a7-b839-1e1c86d6f763",
            "sourceColumn": "[SecurityFilteringBehavior]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f06e00e9-fcfc-479c-9a3a-d705847e5e3c",
        "partitions": [
          {
            "name": "View_Relation",
            "mode": "import",
            "source": {
              "expression": "INFO.VIEW.RELATIONSHIPS()",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "resignation_prediction",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "094d7d87-5728-40f9-9b65-51e995618d68",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Prediction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "306702c0-2408-418c-b0fe-9c252e8b81f0",
            "sourceColumn": "Actual Prediction",
            "summarizeBy": "none"
          },
          {
            "name": "Resignation Probability",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "72526d5b-4773-4505-9bc2-2c182cc2bdee",
            "sourceColumn": "Resignation Probability",
            "summarizeBy": "none"
          },
          {
            "name": "Resignation Prediction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b13feb2-241a-4769-9afe-4fc22d9086e4",
            "sourceColumn": "Resignation Prediction",
            "summarizeBy": "none"
          },
          {
            "name": "Risk Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    resignation_prediction[Resignation Probability] < .05, \"Will not resign\",",
              "    resignation_prediction[Resignation Probability] <= .20, \"Very Low\",",
              "    resignation_prediction[Resignation Probability] <= .4, \"Low\",",
              "    resignation_prediction[Resignation Probability] <= .6, \"Moderate\",",
              "    resignation_prediction[Resignation Probability] <= .8, \"High\",",
              "    \"Very High\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0e6631ab-a04a-47d7-8b93-dbaf5b42db22",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "24b5c18d-87f2-415d-bf65-36f89420f2c8",
        "partitions": [
          {
            "name": "resignation_prediction",
            "mode": "import",
            "queryGroup": "Data\\other",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" &\"\\99999 predicted_resignations.csv\"),[Delimiter=\",\", Columns=45, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Promoted Headers\",{\"Employee ID\", \"Full Name\", \"Resignation Probability\", \"Resignation Prediction\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Removed Other Columns\",{\"Employee ID\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"Full Name\", type text}, {\"Resignation Prediction\", Int64.Type}, {\"Resignation Probability\", Percentage.Type}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Full Name\"}, fact_employee, {\"Full Name\"}, \"fact_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded fact_employee\" = Table.ExpandTableColumn(#\"Merged Queries\", \"fact_employee\", {\"Employee ID\", \"Current Employment Status\"}, {\"Employee ID\", \"Current Employment Status\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded fact_employee\",{\"Employee ID\", \"Current Employment Status\", \"Full Name\", \"Resignation Probability\", \"Resignation Prediction\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Current Employment Status\", \"Actual Prediction\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"Active\",\"0\",Replacer.ReplaceText,{\"Actual Prediction\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Resigned\",\"1\",Replacer.ReplaceText,{\"Actual Prediction\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Actual Prediction\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Full Name\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Employee ID\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Removed Duplicates\", {\"Employee ID\"})",
                "in",
                "    #\"Removed Duplicates1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "f1 score",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "F1 Not Resigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "64431ac5-2d43-4c23-a12d-99ee8c26f119",
            "sourceColumn": "F1 Not Resigned",
            "summarizeBy": "sum"
          },
          {
            "name": "F1 Resigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2a24368b-a1c3-4d8e-82fe-9591f77d7016",
            "sourceColumn": "F1 Resigned",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "93175efc-d45e-4c02-9f61-18dc8dcdd152",
        "partitions": [
          {
            "name": "f1 score",
            "mode": "import",
            "queryGroup": "Data\\other",
            "source": {
              "expression": [
                "let",
                "    Source = resignation_prediction,",
                "    #\"Run Python script\" = Python.Execute(\"from sklearn.metrics import classification_report#(lf)import pandas as pd#(lf)#(lf)# Replace 'dataset' with the name of your input dataset in Power BI#(lf)df = dataset#(lf)#(lf)# Extract actual and predicted labels#(lf)y_test = df['Actual Prediction']#(lf)y_predict = df['Resignation Prediction']#(lf)#(lf)# Generate classification report#(lf)report = classification_report(y_test, y_predict, output_dict=True)#(lf)#(lf)# Extract F1-scores for each class#(lf)f1_scores = {#(lf)    \"\"Class\"\": [\"\"Not Resigned (0)\"\", \"\"Resigned (1)\"\"],#(lf)    \"\"F1-Score\"\": [report[\"\"0\"\"][\"\"f1-score\"\"], report[\"\"1\"\"][\"\"f1-score\"\"]]#(lf)}#(lf)#(lf)# Convert to DataFrame for Power BI#(lf)f1_df = pd.DataFrame(f1_scores)#(lf)\",[dataset=Source]),",
                "    f1_df = #\"Run Python script\"{[Name=\"f1_df\"]}[Value],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(f1_df,{{\"F1-Score\", Percentage.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Not Resigned (0)\",\"F1 Not Resigned\",Replacer.ReplaceText,{\"Class\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Resigned (1)\",\"F1 Resigned\",Replacer.ReplaceText,{\"Class\"}),",
                "    #\"Pivoted Column\" = Table.Pivot(#\"Replaced Value1\", List.Distinct(#\"Replaced Value1\"[Class]), \"Class\", \"F1-Score\", List.Sum)",
                "in",
                "    #\"Pivoted Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Performance-9Box",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aec93acc-93d2-41bd-95a9-31bbdc5b1c00",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "2018",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba3a9510-96d5-47f2-bcea-c2377af244ca",
            "sourceColumn": "2018",
            "summarizeBy": "sum"
          },
          {
            "name": "2019",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd0044ba-2fa1-4158-8d18-aa030633ee63",
            "sourceColumn": "2019",
            "summarizeBy": "sum"
          },
          {
            "name": "2020",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a4a5022-a656-4b36-b5ee-1da6bd9149ad",
            "sourceColumn": "2020",
            "summarizeBy": "sum"
          },
          {
            "name": "2021",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a547f6c7-dd8f-4d73-a460-f59d02c1cc7d",
            "sourceColumn": "2021",
            "summarizeBy": "sum"
          },
          {
            "name": "2022",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2fda61f-5640-4ad7-aab1-01bbd5192bc8",
            "sourceColumn": "2022",
            "summarizeBy": "sum"
          },
          {
            "name": "2023",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cac2bdc1-544b-4a3f-9446-5ba3c459892d",
            "sourceColumn": "2023",
            "summarizeBy": "sum"
          },
          {
            "name": "2024",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "022ff145-3cb8-4e43-b134-5c67ff938af3",
            "sourceColumn": "2024",
            "summarizeBy": "sum"
          },
          {
            "name": "Average Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "179b1cc2-702f-4012-b9a4-783b21d6d668",
            "sourceColumn": "Average Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d58c9710-0316-47ee-a04d-9a02645e210b",
            "sourceColumn": "Assessment Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Performance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ed51b18-3756-401b-ab7e-5e2f75b0bf43",
            "sourceColumn": "Assessment Performance Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24982119-ce64-467b-8d87-4c562ae29bb4",
        "partitions": [
          {
            "name": "Performance-9Box",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let  ",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Performance Review Year\", \"Employee ID\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Reordered Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Removed Specific Rows\" = Table.SelectRows(#\"Reordered Columns1\", each not List.Contains({328, 447, 462, 2411, 2483, 6073, 6500, 6505}, [Index])),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Specific Rows\",{\"Potential Rating\", \"Index\"}),",
                "    #\"Pivoted Column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\"), List.Distinct(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\")[#\"Performance Review Year\"]), \"Performance Review Year\", \"Performance Rating\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Pivoted Column\",null,0,Replacer.ReplaceValue,{\"2021\", \"2022\", \"2023\", \"2020\", \"2018\", \"2019\", \"2024\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Replaced Value\",{\"Employee ID\", \"2018\", \"2019\", \"2020\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns2\", \"Average Rating\", each let",
                "    NonZeroValues = List.Select({[2018], [2019], [2020], [2021], [2022], [2023], [2024]}, each _ <> 0),",
                "    Average = if List.Count(NonZeroValues) > 0 then List.Average(NonZeroValues) else null",
                "in",
                "    Average),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Average Rating\", type number}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type1\", \"Assessment Performance Rating\", each if [Average Rating] >= 1 and [Average Rating] <= 2 then",
                "        if [Average Rating] > 1.5 then 2 ",
                "        else if [Average Rating] < 1.5 then 1 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >2 and [Average Rating] <3 then",
                "        if [Average Rating] > 2.5 then 3 ",
                "        else if [Average Rating] < 2.5 then 2 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >= 3 and [Average Rating] <= 4 then",
                "        if [Average Rating] > 3.5 then 4 ",
                "        else if [Average Rating] < 3.5 then 3 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >4 and [Average Rating] <= 5 then",
                "        if [Average Rating] > 4.5 then 5 ",
                "        else if [Average Rating] < 4.5 then 4 ",
                "        else [Average Rating]",
                "    else [Average Rating]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Assessment Performance Rating\", type number}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type2\", \"Assessment Performance Category\", each if [Assessment Performance Rating] >= 1 and [Assessment Performance Rating] <= 2 then \"Falling Short\" ",
                "   else if [Assessment Performance Rating] >= 2.5 and [Assessment Performance Rating] <=3.5 then \"On Track\" ",
                "   else if [Assessment Performance Rating] >= 4 and [Assessment Performance Rating] <= 5 then \"Peak Performer\" ",
                "   else null),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Assessment Performance Category\", type text}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Potential-9Box",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75b5d6ec-335a-41da-8d52-75b9bfcac17d",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "2018",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d6ffba1-dc2f-419b-9ecd-e7c616486aae",
            "sourceColumn": "2018",
            "summarizeBy": "none"
          },
          {
            "name": "2018 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74d94cbd-b73c-4887-bcf2-312b7b4e3a82",
            "sourceColumn": "2018 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2019",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "233b3813-3115-4d28-91fb-2e8ddb2561b8",
            "sourceColumn": "2019",
            "summarizeBy": "none"
          },
          {
            "name": "2019 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7aa5c8cd-908c-43fc-a8cd-7f53a34e2cd4",
            "sourceColumn": "2019 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2020",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2906beb0-b4e1-4cf4-94ca-41a215e667ad",
            "sourceColumn": "2020",
            "summarizeBy": "none"
          },
          {
            "name": "2020 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84f385d6-03fc-41da-92bc-b84efa2689f7",
            "sourceColumn": "2020 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2021",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c6df664-28cc-41a7-bced-7af5dad3ea8f",
            "sourceColumn": "2021",
            "summarizeBy": "none"
          },
          {
            "name": "2021 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f19c0ab5-60b2-4896-b1ee-db24145f3662",
            "sourceColumn": "2021 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2022",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8c17f13-86cd-4c9c-b9b6-8a884059dd5e",
            "sourceColumn": "2022",
            "summarizeBy": "none"
          },
          {
            "name": "2022 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50c60153-e50b-46d3-b5ff-abe09b8db652",
            "sourceColumn": "2022 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2023",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca27f632-409d-4b8e-a3a4-933b29943095",
            "sourceColumn": "2023",
            "summarizeBy": "none"
          },
          {
            "name": "2023 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf1eb582-e514-49a8-b93f-0454740f95ac",
            "sourceColumn": "2023 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "2024",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54a26376-3d47-477d-873d-7410816c7ee5",
            "sourceColumn": "2024",
            "summarizeBy": "none"
          },
          {
            "name": "2024 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ba9d7bc-cf1a-43ab-ad0c-c17a26122dea",
            "sourceColumn": "2024 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Average Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "541ccc17-a4ed-4e5c-aaf4-55d29a4902e2",
            "sourceColumn": "Average Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Potential Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1581731b-a98d-4211-8a0f-1616d6332391",
            "sourceColumn": "Assessment Potential Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Potential Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "001d7137-0157-4a43-a8fe-d66414248222",
            "sourceColumn": "Assessment Potential Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7dddd356-48d6-4348-a5c9-60b754522b8c",
        "partitions": [
          {
            "name": "Potential-9Box",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let  ",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Performance Review Year\", \"Employee ID\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Reordered Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Removed Specific Rows\" = Table.SelectRows(#\"Reordered Columns1\", each not List.Contains({328, 447, 462, 2411, 2483, 6073, 6500, 6505}, [Index])),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Specific Rows\",{\"Index\", \"Performance Rating\"}),",
                "    #\"Pivoted Column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\"), List.Distinct(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\")[#\"Performance Review Year\"]), \"Performance Review Year\", \"Potential Rating\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Pivoted Column\",null,\"No Rating\",Replacer.ReplaceValue,{\"2021\", \"2022\", \"2023\", \"2020\", \"2018\", \"2019\", \"2024\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Replaced Value\",{\"Employee ID\", \"2018\", \"2019\", \"2020\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns2\", \"2018 Value\", each if [2018] = \"No Rating\" then 0 else if [2018] = \"Low\" then 1 else if [2018] = \"Moderate\" then 2 else if [2018] = \"High\" then 3 else null),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"2018 Value\", Int64.Type}}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Changed Type1\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2020\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Reordered Columns3\", \"2019 Value\", each if [2019] = \"No Rating\" then 0 else if [2019] = \"Low\" then 1 else if [2019] = \"Moderate\" then 2 else if [2019] = \"High\" then 3 else null),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"2019 Value\", Int64.Type}}),",
                "    #\"Reordered Columns4\" = Table.ReorderColumns(#\"Changed Type2\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2019 Value\", \"2020\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Reordered Columns4\", \"2020 Value\", each if [2020] = \"No Rating\" then 0 else if [2020] = \"Low\" then 1 else if [2020] = \"Moderate\" then 2 else if [2020] = \"High\" then 3 else null),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"2020 Value\", Int64.Type}}),",
                "    #\"Reordered Columns5\" = Table.ReorderColumns(#\"Changed Type3\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2019 Value\", \"2020\", \"2020 Value\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Reordered Columns5\", \"2021 Value\", each if [2021] = \"No Rating\" then 0 else if [2021] = \"Low\" then 1 else if [2021] = \"Moderate\" then 2 else if [2021] = \"High\" then 3 else null),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"2021 Value\", Int64.Type}}),",
                "    #\"Reordered Columns6\" = Table.ReorderColumns(#\"Changed Type4\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2019 Value\", \"2020\", \"2020 Value\", \"2021\", \"2021 Value\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Reordered Columns6\", \"2022 Value\", each if [2022] = \"No Rating\" then 0 else if [2022] = \"Low\" then 1 else if [2022] = \"Moderate\" then 2 else if [2022] = \"High\" then 3 else null),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"2022 Value\", Int64.Type}}),",
                "    #\"Reordered Columns7\" = Table.ReorderColumns(#\"Changed Type5\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2019 Value\", \"2020\", \"2020 Value\", \"2021\", \"2021 Value\", \"2022\", \"2022 Value\", \"2023\", \"2024\"}),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Reordered Columns7\", \"2023 Value\", each if [2023] = \"No Rating\" then 0 else if [2023] = \"Low\" then 1 else if [2023] = \"Moderate\" then 2 else if [2023] = \"High\" then 3 else null),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom5\",{{\"2023 Value\", Int64.Type}}),",
                "    #\"Reordered Columns8\" = Table.ReorderColumns(#\"Changed Type6\",{\"Employee ID\", \"2018\", \"2018 Value\", \"2019\", \"2019 Value\", \"2020\", \"2020 Value\", \"2021\", \"2021 Value\", \"2022\", \"2022 Value\", \"2023\", \"2023 Value\", \"2024\"}),",
                "    #\"Added Custom6\" = Table.AddColumn(#\"Reordered Columns8\", \"2024 Value\", each if [2024] = \"No Rating\" then 0 else if [2024] = \"Low\" then 1 else if [2024] = \"Moderate\" then 2 else if [2024] = \"High\" then 3 else null),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Added Custom6\",{{\"2024 Value\", Int64.Type}}),",
                "    #\"Added Custom7\" = Table.AddColumn(#\"Changed Type7\", \"Average Rating\", each let",
                "    NonZeroValues = List.Select({[2018 Value], [2019 Value], [2020 Value], [2021 Value], [2022 Value], [2023 Value], [2024 Value]}, each _ <> 0),",
                "    Average = if List.Count(NonZeroValues) > 0 then List.Average(NonZeroValues) else null",
                "in",
                "    Average),",
                "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Custom7\",{{\"Average Rating\", type number}}),",
                "    #\"Added Custom8\" = Table.AddColumn(#\"Changed Type8\", \"Assessment Potential Rating\", each if [Average Rating] >= 1 and [Average Rating] <= 2 then",
                "        if [Average Rating] > 1.5 then 2 ",
                "        else if [Average Rating] < 1.5 then 1 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >2 and [Average Rating] <=3 then",
                "        if [Average Rating] > 2.5 then 3 ",
                "        else if [Average Rating] < 2.5 then 2 ",
                "        else [Average Rating]",
                "    else [Average Rating]),",
                "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Custom8\",{{\"Assessment Potential Rating\", type number}}),",
                "    #\"Added Custom9\" = Table.AddColumn(#\"Changed Type9\", \"Assessment Potential Category\", each if [Assessment Potential Rating] >= 1 and [Assessment Potential Rating] <= 1.5 then \"Low\" ",
                "   else if [Assessment Potential Rating] >= 2 and [Assessment Potential Rating] <=2.5 then \"Moderate\" ",
                "   else if [Assessment Potential Rating] = 3 then \"High\" ",
                "   else null),",
                "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Added Custom9\",{{\"Assessment Potential Category\", type text}})",
                "in",
                "    #\"Changed Type10\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "9-Box Grid",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a13e926f-799d-4826-83ee-17db871a3aed",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Assessment Potential Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0c44375c-354b-4906-802d-1f2e7cbeafc8",
            "sourceColumn": "Assessment Potential Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "23754e7e-d7a4-48b6-9df8-df6414faf71e",
            "sourceColumn": "Assessment Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Assessment Potential Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd8a0c05-efda-486a-928d-5fe515122864",
            "sourceColumn": "Assessment Potential Category",
            "summarizeBy": "none"
          },
          {
            "name": "Assessment Performance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbaee9f1-1074-47ab-a93a-1f4654975315",
            "sourceColumn": "Assessment Performance Category",
            "summarizeBy": "none"
          },
          {
            "name": "9-Box Grid Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1e4d76d-b02b-4c72-985d-501fb62b4a2c",
            "sourceColumn": "9-Box Grid Category",
            "summarizeBy": "none"
          },
          {
            "name": "9-Box Grid Placement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c79ffc7b-55a6-4544-bab0-7d7377fd5fd3",
            "sourceColumn": "9-Box Grid Placement",
            "summarizeBy": "sum"
          },
          {
            "name": "Grid Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "295b683d-884a-4a69-b028-490026be830d",
            "sourceColumn": "Grid Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2d94ced6-bb2d-49ad-8c9e-6256f5907a6c",
        "partitions": [
          {
            "name": "9-Box Grid",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let  ",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Performance Review Year\", \"Employee ID\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Reordered Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Potential Rating\"}),",
                "    #\"Removed Specific Rows\" = Table.SelectRows(#\"Reordered Columns1\", each not List.Contains({328, 447, 462, 2411, 2483, 6073, 6500, 6505}, [Index])),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Specific Rows\",{\"Potential Rating\", \"Index\"}),",
                "    #\"Pivoted Column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\"), List.Distinct(Table.TransformColumnTypes(#\"Removed Columns\", {{\"Performance Review Year\", type text}}, \"en-US\")[#\"Performance Review Year\"]), \"Performance Review Year\", \"Performance Rating\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Pivoted Column\",null,0,Replacer.ReplaceValue,{\"2021\", \"2022\", \"2023\", \"2020\", \"2018\", \"2019\", \"2024\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Replaced Value\",{\"Employee ID\", \"2018\", \"2019\", \"2020\", \"2021\", \"2022\", \"2023\", \"2024\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns2\", \"Average Rating\", each let",
                "    NonZeroValues = List.Select({[2018], [2019], [2020], [2021], [2022], [2023], [2024]}, each _ <> 0),",
                "    Average = if List.Count(NonZeroValues) > 0 then List.Average(NonZeroValues) else null",
                "in",
                "    Average),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Average Rating\", type number}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type1\", \"Assessment Performance Rating\", each if [Average Rating] >= 1 and [Average Rating] <= 2 then",
                "        if [Average Rating] > 1.5 then 2 ",
                "        else if [Average Rating] < 1.5 then 1 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >2 and [Average Rating] <3 then",
                "        if [Average Rating] > 2.5 then 3 ",
                "        else if [Average Rating] < 2.5 then 2 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >= 3 and [Average Rating] <= 4 then",
                "        if [Average Rating] > 3.5 then 4 ",
                "        else if [Average Rating] < 3.5 then 3 ",
                "        else [Average Rating]",
                "    else if [Average Rating] >4 and [Average Rating] <= 5 then",
                "        if [Average Rating] > 4.5 then 5 ",
                "        else if [Average Rating] < 4.5 then 4 ",
                "        else [Average Rating]",
                "    else [Average Rating]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Assessment Performance Rating\", type number}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type2\", \"Assessment Performance Category\", each if [Assessment Performance Rating] >= 1 and [Assessment Performance Rating] <= 2 then \"Falling Short\" ",
                "   else if [Assessment Performance Rating] >= 2.5 and [Assessment Performance Rating] <=3.5 then \"On Track\" ",
                "   else if [Assessment Performance Rating] >= 4 and [Assessment Performance Rating] <= 5 then \"Peak Performer\" ",
                "   else null),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Assessment Performance Category\", type text}}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Changed Type3\",{\"Employee ID\", \"Assessment Performance Rating\", \"Assessment Performance Category\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Other Columns1\", {\"Employee ID\"}, #\"Potential-9Box\", {\"Employee ID\"}, \"Potential-9Box\", JoinKind.LeftOuter),",
                "    #\"Expanded Potential-9Box\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Potential-9Box\", {\"Assessment Potential Rating\", \"Assessment Potential Category\"}, {\"Potential-9Box.Assessment Potential Rating\", \"Potential-9Box.Assessment Potential Category\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Potential-9Box\",{{\"Potential-9Box.Assessment Potential Rating\", \"Assessment Potential Rating\"}, {\"Potential-9Box.Assessment Potential Category\", \"Assessment Potential Category\"}}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Employee ID\", \"Assessment Potential Rating\", \"Assessment Performance Rating\", \"Assessment Potential Category\", \"Assessment Performance Category\"}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Reordered Columns3\", \"9-Box Grid Category\", each [Assessment Potential Category] & \"-\" & [Assessment Performance Category]),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"9-Box Grid Category\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type4\", \"9-Box Grid Placement\", each if [#\"9-Box Grid Category\"] = \"Low-Falling Short\" then 1 else if [#\"9-Box Grid Category\"] = \"Low-On Track\" then 2 else if [#\"9-Box Grid Category\"] = \"Low-Peak Performer\" then 3 else if [#\"9-Box Grid Category\"] = \"Moderate-Falling Short\" then 4 else if [#\"9-Box Grid Category\"] = \"Moderate-On Track\" then 5 else if [#\"9-Box Grid Category\"] = \"Moderate-Peak Performer\" then 6 else if [#\"9-Box Grid Category\"] = \"High-Falling Short\" then 7 else if [#\"9-Box Grid Category\"] = \"High-On Track\" then 8 else if [#\"9-Box Grid Category\"] = \"High-Peak Performer\" then 9 else null),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"9-Box Grid Placement\", Int64.Type}}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type5\", \"Custom\", each if [#\"9-Box Grid Placement\"] = 1 then \"Growth Opportunity\" else if [#\"9-Box Grid Placement\"] = 2 then \"Reliable Contributor\" else if [#\"9-Box Grid Placement\"] = 3 then \"Consistent Performer\" else if [#\"9-Box Grid Placement\"] = 4 then \"Emerging Contributor\" else if [#\"9-Box Grid Placement\"] = 5 then \"Core Performer\" else if [#\"9-Box Grid Placement\"] = 6 then \"Rising Potential\" else if [#\"9-Box Grid Placement\"] = 7 then \"Aspiring Performer\" else if [#\"9-Box Grid Placement\"] = 8 then \"High Achiever\" else if [#\"9-Box Grid Placement\"] = 9 then \"Top Talent\" else null),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"Custom\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type6\",{{\"Custom\", \"Grid Name\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Payroll_&_Gap_Analysis",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc316d0057bc46fc9cfed86dcba20836"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "decd62f2-5953-495f-a169-2fe8bb2e8a4b",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ac915648-cc57-4004-bdac-9fb41a2c8fcf",
        "measures": [
          {
            "name": "Cal_AVG_Payroll",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX('Payroll_&_Gap_Analysis',",
              "    'Payroll_&_Gap_Analysis'[Cal_Total_Payroll])"
            ],
            "lineageTag": "40e2123c-7f6b-4d3a-96df-cea1abcc2d86"
          },
          {
            "name": "Cal_House_Rent",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary]*0.4",
            "lineageTag": "64282397-4824-4d4d-b6dd-7b0d7173b0a5"
          },
          {
            "name": "Cal_Basic_Salary",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    Basic_Salary_Payroll,",
              "    Basic_Salary_Payroll[basic_Salary]",
              ")"
            ],
            "lineageTag": "a82c2bd8-331c-4536-8946-8693f4817898"
          },
          {
            "name": "Cal_Gender_Pay_Gap_%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Reg_Avg_Basic], dim_employee[Gender] = \"Male\") - ",
              "    CALCULATE([Reg_Avg_Basic], dim_employee[Gender] = \"Female\"),",
              "    CALCULATE([Reg_Avg_Basic], dim_employee[Gender] = \"Male\"),",
              "    0",
              ")"
            ],
            "lineageTag": "01565665-e7b0-4264-add3-664600c0cdd0"
          },
          {
            "name": "Cal_Insuarence",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary]*0.05",
            "lineageTag": "094cd536-db83-4741-a7b3-601408da4be7"
          },
          {
            "name": "Cal_Meadium_Payroll",
            "expression": "MEDIANX('Payroll_&_Gap_Analysis','Payroll_&_Gap_Analysis'[Cal_Total_Payroll])",
            "lineageTag": "05efe2bb-d7f9-4d5a-9414-be7c073a2a8a"
          },
          {
            "name": "Cal_Salary_Growth_%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Cal_Basic_Salary] - [Cal_Previous_Basic_Salary], [Cal_Previous_Basic_Salary], 0)",
            "lineageTag": "e82096b5-00d8-4798-a9db-68aaca6e2926"
          },
          {
            "name": "Cal_Tax",
            "expression": "[Cal_Total_Payable]*0.009",
            "lineageTag": "810c5d0b-68dc-4723-9d6f-b8ada4280fad"
          },
          {
            "name": "Cal_Total_Payable",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary]+[Cal_House_Rent]+[Cal_Insuarence]+ [Cal_Provident_Fund]",
            "lineageTag": "be7bb92f-0ca2-4e02-9ae7-e138bed61f88"
          },
          {
            "name": "Cal_Total_Payroll",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Total_Payable]-[Cal_Tax]-[Cal_Provident_Fund]-[Cal_Insuarence]",
            "lineageTag": "3b2e5fed-a7fc-48f5-bbdc-e9424f3b0a3e"
          },
          {
            "name": "Equity_Above_Benchmark_Gender_%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    COUNTROWS(",
              "        FILTER(",
              "            ALL(fact_employee),",
              "            fact_employee[Base Salary ($)] > ",
              "            CALCULATE(",
              "                AVERAGEX(ALL(fact_employee), fact_employee[Base Salary ($)]),",
              "                fact_employee[Gender] = \"Female\"",
              "            )",
              "        )",
              "    ),",
              "    COUNTROWS(ALL(fact_employee)),",
              "    0",
              ")"
            ],
            "lineageTag": "c7cc7aef-7ed1-480b-a46c-53364dedc3b6"
          },
          {
            "name": "Filter_Slicer",
            "expression": "IF(DISTINCTCOUNT(fact_employee[Employee ID])>0,1,0)",
            "formatString": "0",
            "lineageTag": "35eb7f1c-58bc-4000-84f9-891252e2f0d5"
          },
          {
            "name": "Gap_Eucation_Pay%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE([Cal_AVG_Payroll], fact_employee[Education Level]= \"\") - ",
              "    CALCULATE([Cal_AVG_Payroll], fact_employee[Education Level] = \"\"),",
              "    CALCULATE([Cal_AVG_Payroll], fact_employee[Education Level] = \"\"),",
              "    0",
              ")"
            ],
            "lineageTag": "a5bcaa42-4718-4bbe-ac95-0ef009caec52"
          },
          {
            "name": "Graph_Median_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "PERCENTILE.INC(fact_employee[Base Salary ($)],0.5)",
            "lineageTag": "880deb75-b27b-4cff-9763-9c4015cd4303"
          },
          {
            "name": "Cal_Min_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(fact_employee[Base Salary ($)])",
            "lineageTag": "3bd469ca-db60-4285-adbd-97a0b6051e63"
          },
          {
            "name": "Cal_Overtime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary]*1.5*(Sum(fact_performance[Overtime])/ (8*5*4*12))",
            "lineageTag": "d8d27e89-e716-4a98-85d1-8f3b2bea3056"
          },
          {
            "name": "Cal_Previous_Basic_Salary",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Cal_Basic_Salary],",
              "    DATEADD('date'[Date], -1, YEAR)",
              ")"
            ],
            "lineageTag": "518e3845-0499-4f72-bb73-60f6ed4cddc2"
          },
          {
            "name": "Cal_Previous_Period",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('date'[Date]),",
              "    FILTER(",
              "        ALLEXCEPT('date', 'date'[Year]),",
              "        DATEADD('date'[Year], -2, YEAR) = MAX('date'[Year])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "56dc04af-43d6-4fc0-b3b7-25bb74261ef2"
          },
          {
            "name": "Cal_Provident_Fund",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary]*0.05",
            "lineageTag": "91d06f52-f792-441b-9690-918f7ef4a9e3"
          },
          {
            "name": "Graph_Q1_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "PERCENTILE.INC(fact_employee[Base Salary ($)],0.25)",
            "lineageTag": "351537f5-2196-4215-bc23-2183fef6929d"
          },
          {
            "name": "Graph_Q3_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "PERCENTILE.INC(fact_employee[Base Salary ($)],0.75)",
            "lineageTag": "a6225ab6-a41b-4252-b742-0131eb7bc546"
          },
          {
            "name": "Cal_Max_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MAX(fact_employee[Base Salary ($)])",
            "lineageTag": "892a04be-3000-41c5-8db6-337b0a65c13f"
          },
          {
            "name": "Previous_Period",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('date'[Date]),",
              "    FILTER(",
              "        ALLEXCEPT('date', 'date'[Year]),",
              "        DATEADD('date'[Year], -2, YEAR) = MAX('date'[Year])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d04c4a2d-e5ee-4a8a-94e6-3e2ab224b2e2"
          },
          {
            "name": "Slope_Salary_Year",
            "expression": [
              "",
              "    VAR Line = ",
              "        LINESTX(",
              "            SUMMARIZE(",
              "                'date',",
              "                'date'[Year],                         -- Group by Year",
              "                \"x_value\", 'date'[Year],              -- X-axis values (Year)",
              "                \"y_value\", 'Payroll_&_Gap_Analysis'[Cal_Total_Payroll]  -- Y-axis values (Salary measure)",
              "            ),",
              "            [x_value],                                -- Independent variable (Year)",
              "            [y_value]                                 -- Dependent variable (Total Payroll)",
              "        )",
              "RETURN",
              "    INDEX(Line, 2)  -- The slope (coefficient) is the second value returned by LINESTX",
              ""
            ],
            "lineageTag": "6fa839e4-95c7-4af1-8fb3-70144a59c4ed"
          },
          {
            "name": "Var_Salary_Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        STDEV.P(Basic_Salary_Payroll[basic_Salary]),",
              "        AVERAGE(Basic_Salary_Payroll[basic_Salary])",
              "    )"
            ],
            "lineageTag": "53d54cd1-3b18-461d-b61a-e6aae0c704de"
          },
          {
            "name": "Var_StandardDeviation_Payroll",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "STDEVX.P(",
              "Basic_Salary_Payroll,Basic_Salary_Payroll[basic_Salary]",
              ")",
              ""
            ],
            "lineageTag": "0cdf6626-624e-465e-b9d0-deff21f9f200"
          },
          {
            "name": "Measure 8",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "25d85e50-58de-443d-b86c-b948248aa354"
          },
          {
            "name": "Measure 9",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "6faf632e-d345-4056-844a-6febf004ab53"
          },
          {
            "name": "Graph_Min_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(fact_employee[Base Salary ($)])",
            "lineageTag": "8928420b-2758-4553-b61b-8dff0f278664"
          },
          {
            "name": "StandardizedResiduals",
            "expression": [
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "34e36312-c793-4b2a-9ee7-bd956415c118"
          },
          {
            "name": "Reg_Avg_Basic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(Basic_Salary_Payroll[basic_Salary])",
            "lineageTag": "f9661daa-3a17-4259-9547-3f6e6e53dd96"
          },
          {
            "name": "Reg_Avg_Work_Exp",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(Basic_Salary_Payroll[Work_Experiance])",
            "lineageTag": "7c743367-4af0-41c5-88c8-d4b819050f70"
          },
          {
            "name": "Reg_Covariance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    Basic_Salary_Payroll,",
              "    (Basic_Salary_Payroll[Work_Experiance] - [Reg_Avg_Work_Exp]) * (Basic_Salary_Payroll[basic_Salary] - [Reg_Avg_Basic])",
              ")",
              ""
            ],
            "lineageTag": "bc38eb3e-0c48-4907-965b-222de8683819"
          },
          {
            "name": "Reg_Variance_Work_Experiance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    Basic_Salary_Payroll,",
              "    (Basic_Salary_Payroll[Work_Experiance] - [Reg_Avg_Work_Exp])^2",
              ")"
            ],
            "lineageTag": "b9f6829c-f8ba-4662-abeb-ffb77151e991"
          },
          {
            "name": "Reg_Slope",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Reg_Covariance],[Reg_Variance_Work_Experiance])",
            "lineageTag": "99607d06-a9f7-49ce-8a05-13ec63528fe8"
          },
          {
            "name": "Reg_Intercept",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Reg_Avg_Basic] - ([Reg_Slope] * [Reg_Avg_Work_Exp])",
            "lineageTag": "a1a17756-26aa-4e71-b1d3-925d22b87797"
          },
          {
            "name": "Regression_Line",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Reg_Slope] * MAX(Basic_Salary_Payroll[Work_Experiance]) + [Reg_Intercept]"
            ],
            "lineageTag": "8fedb753-9044-4b96-9fff-fb6ad0752279"
          },
          {
            "name": "Gap_Predicted_Salary",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[Reg_Slope] * MAX(Basic_Salary_Payroll[Work_Experiance]) + [Reg_Intercept]",
              ""
            ],
            "lineageTag": "6f0e12f6-7001-4752-8607-4ca7959061a0"
          },
          {
            "name": "Gap_Salary_Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Cal_Basic_Salary] - [Gap_Predicted_Salary]",
            "lineageTag": "6c4524bc-0ff8-4f7a-a721-b18208094551"
          },
          {
            "name": "Gap_Percent_Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Gap_Salary_Variance], [Gap_Predicted_Salary], 0)",
            "lineageTag": "73c592f4-1529-4710-ab63-8d3ac5383792"
          }
        ],
        "partitions": [
          {
            "name": "Payroll_&_Gap_Analysis",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Basic_Salary_Payroll",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "849195fa96b3499d8e19c43fc2f4cfbe"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6c6b4877-f1e0-422e-acf6-a81699f95edd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d1430814-9ce3-43a7-8225-9494ea7f6b06",
            "sourceColumn": "[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "58d0eb06-792b-489b-86fc-cd9bb36a710d",
            "sourceColumn": "[Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5c639763-aab4-40c0-ac60-95ac616ff339",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d7f24a39-b63b-4b24-84f1-ea2960734764",
            "sourceColumn": "fact_employee[Employee ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Start_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": "LOOKUPVALUE(fact_employee[Hire Date],fact_employee[Employee ID],Basic_Salary_Payroll[Employee ID]) ",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "27fd7314-4d95-4bb0-b79c-b44e5b827a79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Resigned_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "LOOKUPVALUE(fact_resigned[Resigned Date],fact_employee[Employee ID],Basic_Salary_Payroll[Employee ID])"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "7a70febc-f647-4374-b2f4-856260cc832c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Last_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(Basic_Salary_Payroll[Resigned_Date]), ",
              "    TODAY(), ",
              "    Basic_Salary_Payroll[Resigned_Date]",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "47f3275e-e131-459a-a534-11c513888b56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Basic_without_Increament",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "    if ( ",
              "        Basic_Salary_Payroll[Date]>=Basic_Salary_Payroll[Start_Date] && Basic_Salary_Payroll[Date]<=Basic_Salary_Payroll[Last_Date],",
              "            LOOKUPVALUE(fact_employee[Base Salary ($)],fact_employee[Employee ID],Basic_Salary_Payroll[Employee ID]),",
              "    0",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1e8f994d-49a7-42af-935f-c1f2a6e6c477",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Promotion_Factor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "LOOKUPVALUE(fact_employee[Times Promoted],fact_employee[Employee ID],Basic_Salary_Payroll[Employee ID])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b9ade480-c7b7-4999-ae35-ec840e915509",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Promotion_First",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "VAR Current_Date = TODAY()",
              "RETURN ",
              "IF(",
              "    ISBLANK(Basic_Salary_Payroll[Resigned_Date]),",
              "    SWITCH(",
              "        TRUE(),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 1, EDATE(Current_Date, -12),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 2, EDATE(Current_Date, -24),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 3, EDATE(Current_Date, -36),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 4, EDATE(Current_Date, -48),",
              "        BLANK()",
              "    ),",
              "    SWITCH(",
              "        TRUE(),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 1, EDATE(Basic_Salary_Payroll[Last_Date], -12),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 2, EDATE(Basic_Salary_Payroll[Last_Date], -24),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 3, EDATE(Basic_Salary_Payroll[Last_Date], -36),",
              "        Basic_Salary_Payroll[Promotion_Factor] = 4, EDATE(Basic_Salary_Payroll[Last_Date], -48),",
              "        BLANK()",
              "    )",
              ")",
              ""
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "b7192a88-79b5-487a-bb21-0a726a7065fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Promoted_Date_Cal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(",
              "    Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=1 && Basic_Salary_Payroll[Promotion_Factor]=1,1,",
              "        IF(",
              "        Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=1 && Basic_Salary_Payroll[Promotion_Factor]=2,1,",
              "        IF(",
              "        Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=2 && Basic_Salary_Payroll[Promotion_Factor]=2,2,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=1 && Basic_Salary_Payroll[Promotion_Factor]=3,1,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=2 && Basic_Salary_Payroll[Promotion_Factor]=3,2,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=3 && Basic_Salary_Payroll[Promotion_Factor]=3,3,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=1 && Basic_Salary_Payroll[Promotion_Factor]=4,1,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=2 && Basic_Salary_Payroll[Promotion_Factor]=4,2,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]=3 && Basic_Salary_Payroll[Promotion_Factor]=4,3,",
              "            IF(",
              "            Basic_Salary_Payroll[Date]-Basic_Salary_Payroll[Promotion_First]>=4 && Basic_Salary_Payroll[Promotion_Factor]=4,4,",
              "            0",
              "            ",
              "            ))))))))))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "62677a33-5f4f-4789-b54e-ca915d4762e6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Basic_With_Increament",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "Basic_Salary_Payroll[Basic_without_Increament]*((1+0.1)^Basic_Salary_Payroll[Promoted_Date_Cal])",
            "isDataTypeInferred": true,
            "lineageTag": "75622e3f-5abe-4a10-b6c7-7a153befcd7d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY(Basic_Salary_Payroll[Date]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fc6aa8dc-f59a-43b9-87c2-e7858a26d2e8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DaysInMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "DAY(",
              "    EOMONTH(",
              "        Basic_Salary_Payroll[Date], ",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f84f9bcf-175a-4c64-928f-05fb3567c27d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "basic_Salary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "Basic_Salary_Payroll[Basic_With_Increament]*Basic_Salary_Payroll[DayOfMonth]/Basic_Salary_Payroll[DaysInMonth]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f2c293af-52ec-4b1d-a1f7-f637b1bd3466",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Work_Experiance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF(Basic_Salary_Payroll[Date],Basic_Salary_Payroll[Last_Date],YEAR)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "54b15be4-e4a1-40d3-a053-9dc5aebcbbe2",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "9b57b04b-ce3d-4c7a-93bc-17c52cfc8a77",
        "partitions": [
          {
            "name": "Basic_Salary_Payroll",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    CROSSJOIN(",
                "        CALENDAR(DATE(2018, 1, 1), DATE(2026, 12, 31)),",
                "        DISTINCT(fact_employee[Employee ID]) -- Replace 'Employees'[Employee ID] with your actual table and column name",
                "    ),",
                "    \"Year\", YEAR([Date]),",
                "    \"Month\", MONTH([Date]),",
                "    \"Month Name\", FORMAT([Date], \"MMM\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Leave Analysis",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bb917989791e4c859048705a2a2e0dc1"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "723418e2-01a7-4a2b-aeba-efdd32741100",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2baba153-66ea-4ce0-9f87-eb3b68eb3f11",
        "measures": [
          {
            "name": "Avg days on leave",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(fact_leave[Days on Leave])",
            "lineageTag": "c8d24f6b-b3aa-488a-b8e0-ba50986cac74"
          },
          {
            "name": "Total Leave Days",
            "expression": "SUM(fact_leave[Days on Leave])",
            "formatString": "0",
            "lineageTag": "d8676c66-9704-4b91-af53-b903b718b6a7"
          },
          {
            "name": "Average Total Leave Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(fact_leave[Days on Leave])",
            "lineageTag": "c3987d6a-8a41-4946-8f28-0bf5bb35fc20"
          },
          {
            "name": "Annual Leave Balance",
            "expression": "[Total Annual leave]-MAX(fact_leave[Annual Leave Entitlement])",
            "formatString": "0",
            "lineageTag": "f1db0d21-93ba-4722-8f8a-09774a6b6228"
          },
          {
            "name": "Total Annual leave",
            "expression": "CALCULATE(SUM(fact_leave[Days on Leave]),'fact_leave'[Leave Type]=\"Annual\",fact_leave[Leave Status]=\"Approved\")",
            "formatString": "0",
            "lineageTag": "bfc7c680-e39d-40cb-ac97-e79161d297c6"
          },
          {
            "name": "Total Leave Liability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(fact_leave[Annual Leave Liability])",
            "lineageTag": "38495329-1982-4690-8375-de71df5fc7eb"
          },
          {
            "name": "Average Annual Leave Liability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Leave Liability]/DISTINCTCOUNT(fact_leave[Employee ID])",
            "lineageTag": "760a9da9-7651-4e45-95fe-633a161cdddb"
          },
          {
            "name": "Total Leave Days Selected Year",
            "expression": "CALCULATE([Total Leave Days],YEAR('fact_leave'[Leave Start Date])=SELECTEDVALUE('Date Table For Leave Analysis'[Date]))",
            "formatString": "0",
            "lineageTag": "7a8479e9-e728-4d99-a60e-254772f8ccca"
          },
          {
            "name": "Total Leave Days Previous Year",
            "expression": "CALCULATE([Total Leave Days],YEAR('fact_leave'[Leave Start Date])=SELECTEDVALUE('fact_leave'[Leave Start Date])-1)",
            "formatString": "0",
            "lineageTag": "1bad21e6-5bde-4cfc-ae3e-d61aae071529"
          },
          {
            "name": "Total Employees",
            "expression": "DISTINCTCOUNT(fact_leave[Employee ID])",
            "formatString": "0",
            "lineageTag": "f9d3ac61-9820-4d91-92c4-6d7089f1b9d1"
          },
          {
            "name": "Average Leave Taken",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(fact_leave[Days on Leave])",
            "lineageTag": "8584dc83-31e1-407d-8520-53089de2d0c8"
          },
          {
            "name": "Absenteeism Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(SUM('fact_leave'[Days on Leave]),(1800*260),0)",
            "lineageTag": "fd645021-5c2b-4a02-9609-a0065f3f74ce"
          },
          {
            "name": "Availability Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "100-[Absenteeism Rate]",
            "lineageTag": "09781289-0726-4a10-8581-1cb81177a675"
          },
          {
            "name": "Average Leave Days Taken",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGEX('fact_leave','fact_leave'[Days on Leave])",
            "lineageTag": "6627f427-92de-4ff1-ab58-f9f2d9d3767f"
          },
          {
            "name": "Total Absenteeism Days by Weekday",
            "expression": "SUMX('fact_leave','fact_leave'[Days on Leave]*IF(FORMAT('fact_leave'[Leave Start Date],\"dddd\")=SELECTEDVALUE(fact_leave[Weekday Name]),1,0))",
            "formatString": "0",
            "lineageTag": "1f7561ee-b066-4f5a-b7fb-cfba3035eb3f"
          },
          {
            "name": "Total Absenteeism Cost",
            "expression": "SUM('fact_leave'[Absenteeism Cost Impact ($)])",
            "formatString": "0",
            "lineageTag": "7d50440c-6532-4e36-92e8-1828751dc60a"
          },
          {
            "name": "Leave Type Cost",
            "expression": "SUM(fact_leave[Cost of Leave ($)])",
            "formatString": "0",
            "lineageTag": "39dadbb9-0325-4713-8e50-218069249083"
          },
          {
            "name": "Approved Leaves",
            "expression": "CALCULATE(COUNTROWS('fact_leave'),'fact_leave'[Leave Status]=\"Approved\")",
            "formatString": "0",
            "lineageTag": "df0a5a89-4428-4fa6-9a36-9b0df88c867e"
          },
          {
            "name": "Rejected Leaves",
            "expression": "CALCULATE(COUNTROWS('fact_leave'),'fact_leave'[Leave Status]=\"Rejected\")",
            "formatString": "0",
            "lineageTag": "555d382f-7f4d-4830-be6e-7c4da970b6ff"
          },
          {
            "name": "Pending Leaves",
            "expression": "CALCULATE(COUNTROWS('fact_leave'),'fact_leave'[Leave Status]=\"Pending\")",
            "formatString": "0",
            "lineageTag": "2348f1cb-267e-48d2-b174-a69b539bc2ee"
          },
          {
            "name": "Total Leave Cost by Employee",
            "expression": "CALCULATE(SUM('fact_leave'[Cost of Leave ($)]),ALLEXCEPT('fact_leave',fact_leave[Employee ID]))",
            "formatString": "0",
            "lineageTag": "bdf0d68b-1d67-4284-b831-5cd427910012"
          },
          {
            "name": "Annual Leave Utilization",
            "expression": "DIVIDE(SUM(fact_leave[Days on Leave]),SUM(fact_leave[Annual Leave Entitlement]))*100",
            "formatString": "0",
            "lineageTag": "3b1f1eda-26f9-4260-b121-f28956a455f1"
          },
          {
            "name": "Leave Liability Forecast",
            "expression": "CALCULATE(SUM('fact_leave'[Leave Liability Amount ($)]),DATESINPERIOD('fact_leave'[Leave Start Date],MAX('fact_leave'[Leave Start Date]),12,Month))",
            "formatString": "0",
            "lineageTag": "5627e86f-f734-4b4d-b670-12dc9a32ac66"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "af039c24-9900-449a-8407-c35875841e0d"
          },
          {
            "name": "Risk Of Burnout",
            "expression": "IF(SUM('fact_leave'[Days on Leave])<5,1,0)",
            "formatString": "0",
            "lineageTag": "81eb4913-e25e-4ac2-82dd-afe4ab0caeea"
          },
          {
            "name": "Average Performance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(fact_leave[Performance Rating])",
            "lineageTag": "7cf5c62d-78c7-4232-bb6f-237526f4e38f"
          }
        ],
        "partitions": [
          {
            "name": "Leave Analysis",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date Table For Leave Analysis",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "089abc766166457cb6b1d6a631b6809f"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8bd33f1f-d213-48b9-b999-859e868e9f4b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "cbbd3b54-62e4-445c-95d9-2709ae919f3c",
        "partitions": [
          {
            "name": "Date Table For Leave Analysis",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(fact_leave[Leave Start Date]),MAX(fact_leave[Leave Start Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Profile of Employee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "A. Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7bf82b72-3d23-4b0c-8e8a-307132c874f1",
            "sourceColumn": "A. Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "X. Performance  Review Years",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adef2075-33ff-401a-81c5-927d1db172c9",
            "sourceColumn": "X. Performance  Review Years",
            "summarizeBy": "none"
          },
          {
            "name": "B. Employee ID - Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e168c1b-e5b8-4eee-ba6a-0ff6713cee30",
            "sourceColumn": "B. Employee ID - Text",
            "summarizeBy": "none"
          },
          {
            "name": "C. Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51540566-ab09-4fc7-9387-de4ff202dce0",
            "sourceColumn": "C. Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "E. Date of Birth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9bd264f-78f5-436b-8bb7-e94587ac2983",
            "sourceColumn": "E. Date of Birth",
            "summarizeBy": "none"
          },
          {
            "name": "D. Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d691b8f-7376-497a-ba02-531e703d1291",
            "sourceColumn": "D. Gender",
            "summarizeBy": "none"
          },
          {
            "name": "I. Education Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43346017-28a4-4674-92ea-85bf167f19e6",
            "sourceColumn": "I. Education Level",
            "summarizeBy": "none"
          },
          {
            "name": "J. Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "01800a46-f993-4a1b-8157-d7f52668f50b",
            "sourceColumn": "J. Hire Date",
            "summarizeBy": "none"
          },
          {
            "name": "K. Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c6c7a60-f54a-49b5-bb58-52534f5f5692",
            "sourceColumn": "K. Department",
            "summarizeBy": "none"
          },
          {
            "name": "L. Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4a8805f-7235-461c-8d63-532e673d3049",
            "sourceColumn": "L. Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "N. Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9770ba0-eccb-4611-8620-b7a6c2fe96c5",
            "sourceColumn": "N. Region",
            "summarizeBy": "none"
          },
          {
            "name": "O. Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f987ee60-1e9f-438e-90f9-79f00c853dad",
            "sourceColumn": "O. Country",
            "summarizeBy": "none"
          },
          {
            "name": "S. Employment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "241751dc-b7f2-4383-8257-e6b3e958d667",
            "sourceColumn": "S. Employment Status",
            "summarizeBy": "none"
          },
          {
            "name": "R. Employment Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcb2b15e-44e0-4754-88d9-7ec5348d5dfc",
            "sourceColumn": "R. Employment Type",
            "summarizeBy": "none"
          },
          {
            "name": "U. Base Salary ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc0a364d-d751-474f-bebf-1fe2c7fa9029",
            "sourceColumn": "U. Base Salary ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "V. Times Promoted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb1ffffc-1afb-474e-b265-3dc42a69b754",
            "sourceColumn": "V. Times Promoted",
            "summarizeBy": "sum"
          },
          {
            "name": "T. Current Employment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80682166-2261-465c-baa4-3e9b5ed29f8e",
            "sourceColumn": "T. Current Employment Status",
            "summarizeBy": "none"
          },
          {
            "name": "W. Annual Leave Entitlement (days)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ec57379-1d94-4dba-a44a-363ca63f5cf2",
            "sourceColumn": "W. Annual Leave Entitlement (days)",
            "summarizeBy": "sum"
          },
          {
            "name": "G. Age Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "871ad72c-a2b9-4739-80f1-a5e1e75dffc1",
            "sourceColumn": "G. Age Category",
            "summarizeBy": "none"
          },
          {
            "name": "Y. Assessment Potential Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "075e9763-3056-4be3-893c-a30e653825d5",
            "sourceColumn": "Y. Assessment Potential Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "AA. Assessment Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2ea3086-bb45-4bff-8d68-73569399ae10",
            "sourceColumn": "AA. Assessment Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Z. Assessment Potential Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6492cf3-f883-401b-aff9-ca134beb6b37",
            "sourceColumn": "Z. Assessment Potential Category",
            "summarizeBy": "none"
          },
          {
            "name": "AB. Assessment Performance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78b5d806-22d4-4268-b947-41af1e8c4bea",
            "sourceColumn": "AB. Assessment Performance Category",
            "summarizeBy": "none"
          },
          {
            "name": "AC. 9-Box Grid Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "511ac6d7-5804-47eb-8f12-4e157a30ec83",
            "sourceColumn": "AC. 9-Box Grid Category",
            "summarizeBy": "none"
          },
          {
            "name": "AD. 9-Box Grid Placement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0171574f-a439-44e3-bac0-337f35cdb62d",
            "sourceColumn": "AD. 9-Box Grid Placement",
            "summarizeBy": "sum"
          },
          {
            "name": "AE. Grid Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d56fc055-6eb5-45a5-8f03-c9b5c8a35785",
            "sourceColumn": "AE. Grid Name",
            "summarizeBy": "none"
          },
          {
            "name": "AF. Resignation Probability",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9bfb1581-f3ee-4631-8756-4d6863244478",
            "sourceColumn": "AF. Resignation Probability",
            "summarizeBy": "sum"
          },
          {
            "name": "AG. Resignation Probability - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c96325d1-e362-403b-b83e-c525d939a82c",
            "sourceColumn": "AG. Resignation Probability - Copy",
            "summarizeBy": "sum"
          },
          {
            "name": "AH. Resignation Probability Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc6400ae-13a9-45a5-b614-91c8e53c9a7e",
            "sourceColumn": "AH. Resignation Probability Category",
            "summarizeBy": "none"
          },
          {
            "name": "M. Organization Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb8c226e-239b-48bc-9753-bebdc5936804",
            "sourceColumn": "M. Organization Level",
            "summarizeBy": "none"
          },
          {
            "name": "P. Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3a000131-a85d-439c-8464-7f67229811a1",
            "sourceColumn": "P. Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Q. Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9eb8f5ee-83e6-4329-82c8-0d9947ae6df5",
            "sourceColumn": "Q. Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "H. Ethnicity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddf6c451-9663-438f-81a6-b113a8b4394f",
            "sourceColumn": "H. Ethnicity",
            "summarizeBy": "none"
          },
          {
            "name": "F. Age by Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1eda6728-402c-45f4-ad88-01547a862515",
            "sourceColumn": "F. Age by Year",
            "summarizeBy": "sum"
          },
          {
            "name": "AI. Total Projects Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f5ab426-d091-4713-b616-fe4b75c54371",
            "sourceColumn": "AI. Total Projects Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "AJ. Total Project Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3aa2a10c-23a6-4cce-aa60-78ecb42d13f1",
            "sourceColumn": "AJ. Total Project Target",
            "summarizeBy": "sum"
          },
          {
            "name": "AK. Total Working Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cb7e84f-7b70-433f-b778-0ee3cd61ff04",
            "sourceColumn": "AK. Total Working Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "AL. Total Overtime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a018045d-e746-4360-8bc7-b0bceb330eed",
            "sourceColumn": "AL. Total Overtime",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8c2b2965-eeb0-4753-b286-db0c311efcc5",
        "partitions": [
          {
            "name": "Profile of Employee",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"), [Delimiter = \",\", Columns = 12, Encoding = 1252, QuoteStyle = QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Employee ID\"}, dim_employee, {\"Employee ID\"}, \"dim_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_employee\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dim_employee\", {\"Full Name\"}, {\"dim_employee.Full Name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded dim_employee\", {{\"dim_employee.Full Name\", \"Full Name\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\", {\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Reordered Columns\", {\"Employee ID\", \"Performance Review Year\"}),",
                "",
                "    // Group data by Employee ID",
                "    #\"Grouped Rows\" = Table.Group(",
                "        #\"Removed Other Columns\",",
                "        {\"Employee ID\"},",
                "        {{\"Performance Years\", each Text.Combine(List.Transform([Performance Review Year], Text.From), \", \"), type text}}",
                "    ),",
                "",
                "    #\"Sorted Rows\" = Table.Sort(#\"Grouped Rows\", {{\"Employee ID\", Order.Ascending}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Sorted Rows\", {\"Employee ID\"}, fact_employee, {\"Employee ID\"}, \"fact_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded fact_employee\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"fact_employee\", {\"Full Name\", \"Date of Birth\", \"Gender\", \"Education Level\", \"Hire Date\", \"Department\", \"Job Title\", \"Organization Level\", \"Region\", \"Country\", \"Latitude\", \"Longitude\", \"Employment Status\", \"Employment Type\", \"Base Salary ($)\", \"Times Promoted\", \"Current Employment Status\", \"Annual Leave Entitlement (days)\", \"Ethnicity\", \"Age by Year\", \"Age Category\"}, {\"Full Name\", \"Date of Birth\", \"Gender\", \"Education Level\", \"Hire Date\", \"Department\", \"Job Title\", \"Organization Level\", \"Region\", \"Country\", \"Latitude\", \"Longitude\", \"Employment Status\", \"Employment Type\", \"Base Salary ($)\", \"Times Promoted\", \"Current Employment Status\", \"Annual Leave Entitlement (days)\", \"Ethnicity\", \"Age by Year\", \"Age Category\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Expanded fact_employee\", {\"Employee ID\"}, #\"9-Box Grid\", {\"Employee ID\"}, \"9-Box Grid\", JoinKind.LeftOuter),",
                "    #\"Expanded 9-Box Grid\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"9-Box Grid\", {\"Assessment Potential Rating\", \"Assessment Performance Rating\", \"Assessment Potential Category\", \"Assessment Performance Category\", \"9-Box Grid Category\", \"9-Box Grid Placement\", \"Grid Name\"}, {\"Assessment Potential Rating\", \"Assessment Performance Rating\", \"Assessment Potential Category\", \"Assessment Performance Category\", \"9-Box Grid Category\", \"9-Box Grid Placement\", \"Grid Name\"}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Expanded 9-Box Grid\", {\"Employee ID\"}, resignation_prediction, {\"Employee ID\"}, \"resignation_prediction\", JoinKind.LeftOuter),",
                "    #\"Expanded resignation_prediction\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"resignation_prediction\", {\"Resignation Probability\"}, {\"Resignation Probability\"}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Expanded resignation_prediction\", \"Employee ID\", \"Employee ID - Copy\"),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Duplicated Column\",{\"Employee ID\", \"Employee ID - Copy\", \"Performance Years\", \"Full Name\", \"Date of Birth\", \"Gender\", \"Education Level\", \"Hire Date\", \"Department\", \"Job Title\", \"Organization Level\", \"Region\", \"Country\", \"Latitude\", \"Longitude\", \"Employment Status\", \"Employment Type\", \"Base Salary ($)\", \"Times Promoted\", \"Current Employment Status\", \"Annual Leave Entitlement (days)\", \"Ethnicity\", \"Age by Year\", \"Age Category\", \"Assessment Potential Rating\", \"Assessment Performance Rating\", \"Assessment Potential Category\", \"Assessment Performance Category\", \"9-Box Grid Category\", \"9-Box Grid Placement\", \"Grid Name\", \"Resignation Probability\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Reordered Columns1\",{{\"Employee ID - Copy\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type1\",{{\"Employee ID - Copy\", \"Employee ID - Text\"}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Resignation Probability\", \"Resignation Probability - Copy\"),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Duplicated Column1\",{{\"Resignation Probability - Copy\", type number}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type2\", \"Resignation Probability Category\", each if [Resignation Probability] < 0.05 then \"Will not Resign\" else if [Resignation Probability] <= 0.2 then \"Very Low\" else if [Resignation Probability] <= 0.4 then \"Low\" else if [Resignation Probability] <= 0.6 then \"Moderate\" else if [Resignation Probability] <= 0.8 then \"High\" else \"Very High\"),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Resignation Probability Category\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type3\", each true),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Employee ID\", \"A. Employee ID\"}, {\"Employee ID - Text\", \"B. Employee ID - Text\"}, {\"Gender\", \"D. Gender\"}, {\"Date of Birth\", \"E. Date of Birth\"}, {\"Full Name\", \"C. Full Name\"}, {\"Age by Year\", \"F. Age by Year\"}, {\"Age Category\", \"G. Age Category\"}, {\"Ethnicity\", \"H. Ethnicity\"}, {\"Education Level\", \"I. Education Level\"}, {\"Hire Date\", \"J. Hire Date\"}, {\"Department\", \"K. Department\"}, {\"Job Title\", \"L. Job Title\"}, {\"Organization Level\", \"M. Organization Level\"}, {\"Region\", \"N. Region\"}, {\"Country\", \"O. Country\"}, {\"Latitude\", \"P. Latitude\"}, {\"Longitude\", \"Q. Longitude\"}, {\"Employment Type\", \"R. Employment Type\"}, {\"Employment Status\", \"S. Employment Status\"}, {\"Current Employment Status\", \"T. Current Employment Status\"}, {\"Base Salary ($)\", \"U. Base Salary ($)\"}, {\"Times Promoted\", \"V. Times Promoted\"}, {\"Annual Leave Entitlement (days)\", \"W. Annual Leave Entitlement (days)\"}, {\"Performance Years\", \"X. Performance Years\"}, {\"Assessment Potential Rating\", \"Y. Assessment Potential Rating\"}, {\"Assessment Potential Category\", \"Z. Assessment Potential Category\"}, {\"Assessment Performance Rating\", \"AA. Assessment Performance Rating\"}, {\"Assessment Performance Category\", \"AB. Assessment Performance Category\"}, {\"9-Box Grid Category\", \"AC. 9-Box Grid Category\"}, {\"9-Box Grid Placement\", \"AD. 9-Box Grid Placement\"}, {\"Grid Name\", \"AE. Grid Name\"}, {\"Resignation Probability\", \"AF. Resignation Probability\"}, {\"Resignation Probability - Copy\", \"AG. Resignation Probability - Copy\"}, {\"Resignation Probability Category\", \"AH. Resignation Probability Category\"}}),",
                "    #\"Added Prefix\" = Table.TransformColumns(#\"Renamed Columns2\", {{\"X. Performance Years\", each \"Years: \" & _, type text}}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Prefix\",{{\"X. Performance Years\", \"X. Performance  Review Years\"}}),",
                "    #\"Merged Queries4\" = Table.NestedJoin(#\"Renamed Columns3\", {\"A. Employee ID\"}, #\"Handled+Targeted+Working Hours+Overtime\", {\"Employee ID\"}, \"Handle+Target+Working Hours+Overtime\", JoinKind.LeftOuter),",
                "    #\"Expanded Handle+Target+Working Hours+Overtime\" = Table.ExpandTableColumn(#\"Merged Queries4\", \"Handle+Target+Working Hours+Overtime\", {\"Total Projects Handled\", \"Total Project Target\", \"Total Working Hours\", \"Total Overtime\"}, {\"Total Projects Handled\", \"Total Project Target\", \"Total Working Hours\", \"Total Overtime\"}),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Expanded Handle+Target+Working Hours+Overtime\",{{\"Total Projects Handled\", Int64.Type}, {\"Total Project Target\", Int64.Type}, {\"Total Working Hours\", Int64.Type}, {\"Total Overtime\", Int64.Type}}),",
                "    // Create a blank row with null values for all columns",
                "    BlankRow = Record.FromList(",
                "        List.Transform(Table.Schema(#\"Changed Type4\")[Kind], each try null otherwise null), ",
                "        Table.ColumnNames(#\"Changed Type4\")",
                "    ),",
                "",
                "    // Add the blank row at the top of the table",
                "    #\"Inserted Blank Row\" = Table.InsertRows(#\"Changed Type4\", 0, {BlankRow}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Inserted Blank Row\",null,0,Replacer.ReplaceValue,{\"A. Employee ID\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,\"0\",Replacer.ReplaceValue,{\"B. Employee ID - Text\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,\"Years: 0000\",Replacer.ReplaceValue,{\"X. Performance  Review Years\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",null,\"---\",Replacer.ReplaceValue,{\"C. Full Name\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",null,#date(9999, 12, 31),Replacer.ReplaceValue,{\"E. Date of Birth\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",null,\"---\",Replacer.ReplaceValue,{\"D. Gender\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",null,\"---\",Replacer.ReplaceValue,{\"D. Gender\", \"I. Education Level\", \"J. Hire Date\", \"K. Department\", \"L. Job Title\", \"M. Organization Level\", \"N. Region\", \"O. Country\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",null,0,Replacer.ReplaceValue,{\"P. Latitude\", \"Q. Longitude\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",null,\"---\",Replacer.ReplaceValue,{\"S. Employment Status\", \"R. Employment Type\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",null,0,Replacer.ReplaceValue,{\"U. Base Salary ($)\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",null,0,Replacer.ReplaceValue,{\"V. Times Promoted\"}),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Replaced Value10\",{{\"V. Times Promoted\", Int64.Type}}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Changed Type5\",null,\"---\",Replacer.ReplaceValue,{\"T. Current Employment Status\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",null,0,Replacer.ReplaceValue,{\"W. Annual Leave Entitlement (days)\"}),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Replaced Value12\",{{\"W. Annual Leave Entitlement (days)\", Int64.Type}, {\"A. Employee ID\", Int64.Type}, {\"J. Hire Date\", type date}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type6\", {{\"J. Hire Date\", #date(9999, 12, 31)}}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Errors\",null,\"---\",Replacer.ReplaceValue,{\"H. Ethnicity\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",null,0,Replacer.ReplaceValue,{\"F. Age by Year\"}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Replaced Value14\",{{\"F. Age by Year\", Int64.Type}}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Changed Type7\",null,\"---\",Replacer.ReplaceValue,{\"G. Age Category\", \"Z. Assessment Potential Category\", \"AB. Assessment Performance Category\", \"AC. 9-Box Grid Category\", \"AE. Grid Name\", \"AH. Resignation Probability Category\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",null,0,Replacer.ReplaceValue,{\"Y. Assessment Potential Rating\", \"AA. Assessment Performance Rating\", \"AD. 9-Box Grid Placement\", \"AF. Resignation Probability\", \"AG. Resignation Probability - Copy\", \"Total Projects Handled\", \"Total Project Target\", \"Total Working Hours\", \"Total Overtime\"}),",
                "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Replaced Value16\",{{\"AD. 9-Box Grid Placement\", Int64.Type}, {\"AF. Resignation Probability\", Percentage.Type}, {\"Total Projects Handled\", Int64.Type}, {\"Total Project Target\", Int64.Type}, {\"Total Working Hours\", Int64.Type}, {\"Total Overtime\", Int64.Type}}),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Changed Type8\",{{\"Total Projects Handled\", \"AI. Total Projects Handled\"}, {\"Total Project Target\", \"AJ. Total Project Target\"}, {\"Total Working Hours\", \"AK. Total Working Hours\"}, {\"Total Overtime\", \"AL. Total Overtime\"}})",
                "in",
                "    #\"Renamed Columns4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Information of Age, Assessment Potential, Assessment Performance",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Age Category+Banding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1296949e-4a42-47a5-835d-0cc726617b3a",
            "sourceColumn": "Age Category+Banding",
            "summarizeBy": "none"
          },
          {
            "name": "Assessment Potential Category+Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30181093-7af6-4dec-918c-faa9ab2c0b39",
            "sourceColumn": "Assessment Potential Category+Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Assessment Performance Category+Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fa4c4c8-be53-439b-8967-3f0c8f1c6049",
            "sourceColumn": "Assessment Performance Category+Rating",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e786cf21-b9e5-4e8e-8eff-f576a28fe73e",
        "partitions": [
          {
            "name": "Information of Age, Assessment Potential, Assessment Performance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZBPawIxEMW/ypBThaTo/gnFW6mWHrRdai9l9RDcUYMxkTFL22/fTIRSqoU5zHsz7wczbSveQ++3cN/1Lo7hZnSninogpJiFD5YSRrdZPxrnbFpc7ALFn4mEYiBWshVTQ+4LHgwhEjQUNng62eCNS6uFVmVmzEOHZCKyl5Jn8IuHNzLrPZsMLFPxhKlz26nrzFKrKsef7HbHmvsGzR4apE2gA1JyKwkVM2s48xbobbhgVVrVmfUcYGKi+dXl0z6PSBb9Gru/yVorrf9PNoTqFaMlPKBPT1v2w2GJWl8PrL4B\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Age Category+Banding\" = _t, #\"Assessment Potential Category+Rating\" = _t, #\"Assessment Performance Category+Rating\" = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Only All",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "19ec7a4c-f6f0-4d34-b037-9e3a2ac8be9a",
            "sourceColumn": "Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c61ebf7-eb33-4fab-ada0-8defeb13a1e3",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Review Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "411ae368-a6c9-4481-871f-58ab7c5e9b14",
            "sourceColumn": "Performance Review Year",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "686ab9d9-52ca-4db6-ae26-53f2a3d799dd",
            "sourceColumn": "Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Projects Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "962dba00-323b-4099-8e95-a132f12b9813",
            "sourceColumn": "Projects Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Project Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1fb1f34-85c5-42a6-b19c-bc300d3533e4",
            "sourceColumn": "Project Target",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "32cefa14-f476-42c8-858e-a58b3f95b380",
        "partitions": [
          {
            "name": "Only All",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"), [Delimiter = \",\", Columns = 12, Encoding = 1252, QuoteStyle = QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\", {",
                "        {\"Employee ID\", Int64.Type},",
                "        {\"Performance Review Year\", Int64.Type},",
                "        {\"Performance Rating\", Int64.Type},",
                "        {\"Projects Handled\", Int64.Type},",
                "        {\"Project Target\", Int64.Type},",
                "        {\"Working Hours\", Int64.Type},",
                "        {\"Overtime\", Int64.Type},",
                "        {\"Team Size\", Int64.Type},",
                "        {\"Potential Rating\", type text},",
                "        {\"Satisfaction Score\", Int64.Type},",
                "        {\"Incentive Amount ($)\", type number},",
                "        {\"Bonus ($)\", type number}",
                "    }),",
                "",
                "    // Group by Employee ID and calculate sum of Projects Handled and Project Target",
                "    #\"Grouped Rows\" = Table.Group(#\"Changed Type\", {\"Employee ID\"}, {",
                "        {\"Total Projects Handled\", each List.Sum([Projects Handled]), type number},",
                "        {\"Total Project Target\", each List.Sum([Project Target]), type number}",
                "    }),",
                "",
                "    // Merge employee details for additional columns",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Grouped Rows\", {\"Employee ID\"}, dim_employee, {\"Employee ID\"}, \"dim_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_employee\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dim_employee\", {\"Full Name\"}, {\"Full Name\"}),",
                "",
                "    // Reorder and clean up columns",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded dim_employee\", {\"Employee ID\", \"Full Name\", \"Total Projects Handled\", \"Total Project Target\"}),",
                "",
                "    // Remove Full Name if not needed",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\", {\"Full Name\"}),",
                "",
                "    // Rename columns for clarity",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\", {{\"Total Projects Handled\", \"Projects Handled\"}, {\"Total Project Target\", \"Project Target\"}}),",
                "",
                "    // Add a new column \"All Column\" with the value \"All\" for every row",
                "    #\"Added All Column\" = Table.AddColumn(#\"Renamed Columns\", \"All Column\", each \"All\", type text),",
                "",
                "    // Change type for the final columns",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added All Column\", {{\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type1\",{{\"All Column\", \"Performance Review Year\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Employee ID\", \"Performance Review Year\", \"Projects Handled\", \"Project Target\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Reordered Columns1\", {\"Employee ID\"}, #\"9-Box Grid\", {\"Employee ID\"}, \"9-Box Grid\", JoinKind.LeftOuter),",
                "    #\"Expanded 9-Box Grid\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"9-Box Grid\", {\"Assessment Performance Rating\"}, {\"Assessment Performance Rating\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded 9-Box Grid\",{{\"Assessment Performance Rating\", \"Performance Rating\"}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"Employee ID\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Reordered Columns2\", {\"Employee ID\"}, dim_employee, {\"Employee ID\"}, \"dim_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_employee1\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"dim_employee\", {\"Full Name\"}, {\"Full Name\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Expanded dim_employee1\",{\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Reordered Columns3\",{{\"Employee ID\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Full All",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffd5205d-5079-4458-82d3-daed8419cfe8",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b6567a7-533a-4497-81bd-c622a94e9f91",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Review Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b095467-373a-49c8-9693-df24f29c1ac7",
            "sourceColumn": "Performance Review Year",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63ccd59e-fa9a-4a9d-8aec-ce48d2d5a1ca",
            "sourceColumn": "Performance Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Projects Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b610f891-8990-41f1-973f-3316f0e7f536",
            "sourceColumn": "Projects Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Project Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9eb42e0-3ab6-4563-b949-85a6ee62ced9",
            "sourceColumn": "Project Target",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f9ede4c6-a806-466a-af19-40b0058e4176",
        "partitions": [
          {
            "name": "Full All",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Employee ID\"}, dim_employee, {\"Employee ID\"}, \"dim_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_employee\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dim_employee\", {\"Full Name\"}, {\"dim_employee.Full Name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded dim_employee\",{{\"dim_employee.Full Name\", \"Full Name\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Reordered Columns\", {\"Employee ID\"}, fact_employee, {\"Employee ID\"}, \"fact_employee\", JoinKind.LeftOuter),",
                "    #\"Expanded fact_employee\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"fact_employee\", {\"Job Title\"}, {\"fact_employee.Job Title\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded fact_employee\",{{\"fact_employee.Job Title\", \"Job Title\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Employee ID\", \"Full Name\", \"Job Title\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"Job Title\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"Extra PRoject\", each if[Projects Handled]>[Project Target] then \"Exceeds Target\" else \"On Target\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Extra PRoject\", type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Extra PRoject\", \"Extra Project\"}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"Employee ID\", \"Full Name\", \"Performance Review Year\", \"Performance Rating\", \"Projects Handled\", \"Project Target\", \"Extra Project\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns2\", each true),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Extra Project\", \"Working Hours\", \"Overtime\", \"Team Size\", \"Potential Rating\", \"Satisfaction Score\", \"Incentive Amount ($)\", \"Bonus ($)\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Removed Columns1\", #\"Only All\"})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Handled+Targeted+Working Hours+Overtime",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a6bfb50a-6e8c-4171-b120-99b46c0f6965",
            "sourceColumn": "Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Total Projects Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b94ac16b-f567-4bfb-95c2-ebf536cab00a",
            "sourceColumn": "Total Projects Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Project Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02820d08-0eb6-471f-a067-f35abd328fa1",
            "sourceColumn": "Total Project Target",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Working Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd09fbc0-3521-4013-bfc9-f94a91277904",
            "sourceColumn": "Total Working Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Overtime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad8e5789-0799-41f0-9016-d55f2dbe12f1",
            "sourceColumn": "Total Overtime",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1ac1a9f0-bfde-4800-accc-dc84f8f92149",
        "partitions": [
          {
            "name": "Handled+Targeted+Working Hours+Overtime",
            "mode": "import",
            "queryGroup": "Data\\fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(#\"Folder Path\" & \"\\performance.csv\"), [Delimiter = \",\", Columns = 12, Encoding = 1252, QuoteStyle = QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"Employee ID\", Int64.Type}, {\"Performance Review Year\", Int64.Type}, {\"Performance Rating\", Int64.Type}, {\"Projects Handled\", Int64.Type}, {\"Project Target\", Int64.Type}, {\"Working Hours\", Int64.Type}, {\"Overtime\", Int64.Type}, {\"Team Size\", Int64.Type}, {\"Potential Rating\", type text}, {\"Satisfaction Score\", Int64.Type}, {\"Incentive Amount ($)\", type number}, {\"Bonus ($)\", type number}}),",
                "    ",
                "    // Remove unnecessary columns to focus only on relevant data",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\", {\"Employee ID\", \"Projects Handled\", \"Project Target\", \"Working Hours\", \"Overtime\"}),",
                "",
                "    // Group by Employee ID and calculate the sums for each column",
                "    #\"Grouped Rows\" = Table.Group(",
                "        #\"Removed Other Columns\",",
                "        {\"Employee ID\"},",
                "        {",
                "            {\"Total Projects Handled\", each List.Sum([Projects Handled]), type number},",
                "            {\"Total Project Target\", each List.Sum([Project Target]), type number},",
                "            {\"Total Working Hours\", each List.Sum([Working Hours]), type number},",
                "            {\"Total Overtime\", each List.Sum([Overtime]), type number}",
                "        }",
                "    )",
                "in",
                "    #\"Grouped Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Gender-Ethincity",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "34b6315bf5514c2bb41453d1225ab936"
          }
        ],
        "columns": [
          {
            "name": "Gender-Ethincity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "0959c58f-4e57-4395-aed6-b0e0d1254784",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Gender-Ethincity Fields"
                }
              ]
            },
            "sortByColumn": "Gender-Ethincity Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Gender-Ethincity Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "a3e12263-7a6e-484e-ac46-b754571d3d8a",
            "sortByColumn": "Gender-Ethincity Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Gender-Ethincity Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "67c67f30-96bd-47a9-be8c-056f811398a2",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "54e11295-1a8f-47f3-a6bd-76055e8b1737",
        "partitions": [
          {
            "name": "Gender-Ethincity",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Gender\", NAMEOF('dim_employee'[Gender]), 0),",
                "    (\"Ethnicity\", NAMEOF('dim_employee'[Ethnicity]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Head-hire-resig-attrition",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4494075724f144cead6595cc4e30b246"
          }
        ],
        "columns": [
          {
            "name": "Head-hire-resig-attrition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "9abc9099-bf5b-4576-ac8d-e49377472b9a",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Head-hire-resig-attrition Fields"
                }
              ]
            },
            "sortByColumn": "Head-hire-resig-attrition Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Head-hire-resig-attrition Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "09a9644c-3365-487a-9225-929b7a3ed306",
            "sortByColumn": "Head-hire-resig-attrition Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Head-hire-resig-attrition Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1783cda4-9c71-4a40-bedd-4e3f9185507e",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "eabbbf36-612c-449c-95ec-c3ae22c609ad",
        "partitions": [
          {
            "name": "Head-hire-resig-attrition",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"# of Employee\", NAMEOF('_measure'[Cumulative Employee Count]), 0),",
                "    (\"# of Resignation\", NAMEOF('_measure'[# of Resignation]), 1),",
                "    (\"Hires\", NAMEOF('_measure'[Hires]), 2),",
                "    (\"Overall Attrition Rate\", NAMEOF('_measure'[Overall Attrition Rate]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}